In [ ]:
!pip install pandas openpyxl sentence-transformers chromadb scikit-learn numpy torch -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 kB 2.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 60.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 17.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 65.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.2/17.2 MB 74.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.1/72.1 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 180.2/180.2 kB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.0/69.0 kB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.6/231.6 kB 14.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.6/71.6 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 4.1 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-adk 1.29.0 requires opentelemetry-api<1.39.0,>=1.36.0, but you have opentelemetry-api 1.41.0 which is incompatible.
google-adk 1.29.0 requires opentelemetry-sdk<1.39.0,>=1.36.0, but you have opentelemetry-sdk 1.41.0 which is incompatible.
opentelemetry-exporter-gcp-logging 1.11.0a0 requires opentelemetry-sdk<1.39.0,>=1.35.0, but you have opentelemetry-sdk 1.41.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-exporter-otlp-proto-common==1.38.0, but you have opentelemetry-exporter-otlp-proto-common 1.41.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-proto==1.38.0, but you have opentelemetry-proto 1.41.0 which is incompatible.
opentelemetry-exporter-otlp-proto-http 1.38.0 requires opentelemetry-sdk~=1.38.0, but you have opentelemetry-sdk 1.41.0 which is incompatible.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import TruncatedSVD
import chromadb

In [ ]:
# Path data di Drive
DATA_PATH = "/content/drive/MyDrive/skripsian/data"
TKPI_PATH = f"{DATA_PATH}/tkpi-2019.xlsx"

In [ ]:
import pandas as pd
# Load TKPI
tkpi_df = pd.read_excel(TKPI_PATH, sheet_name="Komposisi Pangan")

# hapus baris pada dataframe dengan NaN
tkpi_df = tkpi_df.dropna(how='all')

# Set nama kolom DataFrame
tkpi_df.columns = ['KODE','NAMA BAHAN','SUMBER','AIR (g)','ENERGI (Kal)','PROTEIN (g)','LEMAK (g)','KH (g)','SERAT (g)','ABU (g)','KALSIUM (mg)','FOSFOR (mg)','BESI (mg)','NATRIUM (mg)','KALIUM (mg)','TEMBAGA (mg)','SENG (mg)','RETINOL (mcg)','B-KAR (mcg)','KAR-TOTAL (mcg)','THIAMIN (mg)','RIBOFLAVIN (mg)','NIASIN (mg)','VIT-C (mg)','BDD (%)']

In [ ]:
print("TKPI berhasil load dari Drive!")
print("Total baris:", len(tkpi_df))
display(tkpi_df.head())

TKPI berhasil load dari Drive!
Total baris: 1177

,KODE,NAMA BAHAN,SUMBER,AIR (g),ENERGI (Kal),PROTEIN (g),LEMAK (g),KH (g),SERAT (g),ABU (g),...,TEMBAGA (mg),SENG (mg),RETINOL (mcg),B-KAR (mcg),KAR-TOTAL (mcg),THIAMIN (mg),RIBOFLAVIN (mg),NIASIN (mg),VIT-C (mg),BDD (%)
2,TUNGGAL/SINGLE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AR001,"Beras giling, mentah",KZGMI-2001,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.10,0.5,0,0,0,0.20,0.08,2.6,0,100.0
4,AR002,"Beras giling var pelita, mentah",KZGPI- 1990,11.4,369.0,9.5,1.4,77.1,0.4,0.6,...,0.00,0.0,0,0,0,0.26,0.00,0.0,0,100.0
5,AR003,"Beras giling var \nrojolele, mentah",KZGPI- 1990,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.14,0.1,NaN,0,80,0.20,0.02,1.5,0,100.0
6,AR004,"Beras hitam, mentah",KZGMI-2001,12.9,351.0,8.0,1.3,76.9,20.1,0.9,...,0.10,1.6,0,0,0,0.21,0.06,0.0,0,100.0

In [ ]:
# Hapus baris yang NAMA BAHAN NaN atau "TUNGGAL/SINGLE"
tkpi_df = tkpi_df.dropna(subset=['NAMA BAHAN'])
tkpi_df = tkpi_df[tkpi_df['NAMA BAHAN'].str.strip() != "TUNGGAL/SINGLE"]

# Reset index
tkpi_df = tkpi_df.reset_index(drop=True)

In [ ]:
import re

def deep_clean_nama_bahan(text):
    if pd.isna(text):
        return ""
    # Ganti \n dan \r dengan spasi
    text = str(text).replace('\n', ' ').replace('\r', ' ')
    # Ganti multiple spasi jadi satu spasi
    text = re.sub(r'\s+', ' ', text)
    # Normalisasi koma (spasi sebelum/sesudah koma)
    text = re.sub(r'\s*,\s*', ', ', text)
    # Strip lagi
    text = text.strip()
    return text

# Terapkan deep cleaning ke kolom nama bahan
tkpi_df['NAMA BAHAN'] = tkpi_df['NAMA BAHAN'].apply(deep_clean_nama_bahan)

# Cek hasilnya (penting! harus kamu lihat)
print("Contoh 20 nama bahan setelah deep cleaning:")
print(tkpi_df['NAMA BAHAN'].head(20).tolist())

display(tkpi_df.head())  # lihat apakah nama sudah rapi

Contoh 20 nama bahan setelah deep cleaning:
['Beras giling, mentah', 'Beras giling var pelita, mentah', 'Beras giling var rojolele, mentah', 'Beras hitam, mentah', 'Beras jagung kuning, kering, mentah', 'Beras jagung putih, kering, mentah', 'Beras ketan hitam tumbuk, mentah', 'Beras ketan putih tumbuk, mentah', 'Beras ladang, mentah', 'Beras menir, mentah', 'Beras parboiled', 'Beras tumbuk, mentah', 'Beras tumbuk merah, mentah', 'Cantel, mentah', 'Jagung muda, kuning, mentah', 'Jagung kuning pipil, kering, mentah', 'Jagung pipil var, harapan, kering', 'Jagung pipil var, metro, kering', 'Jali, mentah', 'Jawawut, mentah']

,KODE,NAMA BAHAN,SUMBER,AIR (g),ENERGI (Kal),PROTEIN (g),LEMAK (g),KH (g),SERAT (g),ABU (g),...,TEMBAGA (mg),SENG (mg),RETINOL (mcg),B-KAR (mcg),KAR-TOTAL (mcg),THIAMIN (mg),RIBOFLAVIN (mg),NIASIN (mg),VIT-C (mg),BDD (%)
0,AR001,"Beras giling, mentah",KZGMI-2001,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.10,0.5,0,0,0,0.20,0.08,2.6,0,100.0
1,AR002,"Beras giling var pelita, mentah",KZGPI- 1990,11.4,369.0,9.5,1.4,77.1,0.4,0.6,...,0.00,0.0,0,0,0,0.26,0.00,0.0,0,100.0
2,AR003,"Beras giling var rojolele, mentah",KZGPI- 1990,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.14,0.1,NaN,0,80,0.20,0.02,1.5,0,100.0
3,AR004,"Beras hitam, mentah",KZGMI-2001,12.9,351.0,8.0,1.3,76.9,20.1,0.9,...,0.10,1.6,0,0,0,0.21,0.06,0.0,0,100.0
4,AR005,"Beras jagung kuning, kering, mentah",KZGMI-2001,10.8,358.0,5.5,0.1,82.7,10.0,0.9,...,0.10,4.1,NaN,641,NaN,0.12,0.08,1.0,3,100.0

In [ ]:
print("Baris invalid dihapus!")
print("Total baris valid:", len(tkpi_df))
display(tkpi_df.head())

Baris invalid dihapus!
Total baris valid: 1146

,KODE,NAMA BAHAN,SUMBER,AIR (g),ENERGI (Kal),PROTEIN (g),LEMAK (g),KH (g),SERAT (g),ABU (g),...,TEMBAGA (mg),SENG (mg),RETINOL (mcg),B-KAR (mcg),KAR-TOTAL (mcg),THIAMIN (mg),RIBOFLAVIN (mg),NIASIN (mg),VIT-C (mg),BDD (%)
0,AR001,"Beras giling, mentah",KZGMI-2001,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.10,0.5,0,0,0,0.20,0.08,2.6,0,100.0
1,AR002,"Beras giling var pelita, mentah",KZGPI- 1990,11.4,369.0,9.5,1.4,77.1,0.4,0.6,...,0.00,0.0,0,0,0,0.26,0.00,0.0,0,100.0
2,AR003,"Beras giling var rojolele, mentah",KZGPI- 1990,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.14,0.1,NaN,0,80,0.20,0.02,1.5,0,100.0
3,AR004,"Beras hitam, mentah",KZGMI-2001,12.9,351.0,8.0,1.3,76.9,20.1,0.9,...,0.10,1.6,0,0,0,0.21,0.06,0.0,0,100.0
4,AR005,"Beras jagung kuning, kering, mentah",KZGMI-2001,10.8,358.0,5.5,0.1,82.7,10.0,0.9,...,0.10,4.1,NaN,641,NaN,0.12,0.08,1.0,3,100.0

In [ ]:
print("1. Shape data:", tkpi_df.shape)
print("2. Kolom tersedia:")
print(tkpi_df.columns.tolist())

print("\n3. Sample 10 baris pertama:")
display(tkpi_df.head(10))

print("\n4. Info data (tipe & missing):")
print(tkpi_df.info())

print("\n5. Missing values per kolom:")
print(tkpi_df.isnull().sum())

print("\n6. Statistik deskriptif gizi utama:")
gizi_cols = ['ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'BESI (mg)', 'VIT-C (mg)', 'KALSIUM (mg)']
print(tkpi_df[gizi_cols].describe())

print("\n7. Bahan dengan protein tertinggi (top 10):")
print(tkpi_df.nlargest(10, 'PROTEIN (g)')[['NAMA BAHAN', 'PROTEIN (g)']])

1. Shape data: (1146, 25)
2. Kolom tersedia:
['KODE', 'NAMA BAHAN', 'SUMBER', 'AIR (g)', 'ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'KH (g)', 'SERAT (g)', 'ABU (g)', 'KALSIUM (mg)', 'FOSFOR (mg)', 'BESI (mg)', 'NATRIUM (mg)', 'KALIUM (mg)', 'TEMBAGA (mg)', 'SENG (mg)', 'RETINOL (mcg)', 'B-KAR (mcg)', 'KAR-TOTAL (mcg)', 'THIAMIN (mg)', 'RIBOFLAVIN (mg)', 'NIASIN (mg)', 'VIT-C (mg)', 'BDD (%)']

3. Sample 10 baris pertama:

,KODE,NAMA BAHAN,SUMBER,AIR (g),ENERGI (Kal),PROTEIN (g),LEMAK (g),KH (g),SERAT (g),ABU (g),...,TEMBAGA (mg),SENG (mg),RETINOL (mcg),B-KAR (mcg),KAR-TOTAL (mcg),THIAMIN (mg),RIBOFLAVIN (mg),NIASIN (mg),VIT-C (mg),BDD (%)
0,AR001,"Beras giling, mentah",KZGMI-2001,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.10,0.5,0,0,0,0.20,0.08,2.6,0,100.0
1,AR002,"Beras giling var pelita, mentah",KZGPI- 1990,11.4,369.0,9.5,1.4,77.1,0.4,0.6,...,0.00,0.0,0,0,0,0.26,0.00,0.0,0,100.0
2,AR003,"Beras giling var rojolele, mentah",KZGPI- 1990,12.0,357.0,8.4,1.7,77.1,0.2,0.8,...,0.14,0.1,NaN,0,80,0.20,0.02,1.5,0,100.0
3,AR004,"Beras hitam, mentah",KZGMI-2001,12.9,351.0,8.0,1.3,76.9,20.1,0.9,...,0.10,1.6,0,0,0,0.21,0.06,0.0,0,100.0
4,AR005,"Beras jagung kuning, kering, mentah",KZGMI-2001,10.8,358.0,5.5,0.1,82.7,10.0,0.9,...,0.10,4.1,NaN,641,NaN,0.12,0.08,1.0,3,100.0
5,AR006,"Beras jagung putih, kering, mentah",KZGMI-2001,22.5,307.0,4.8,0.1,71.8,10.0,0.8,...,0.10,3.5,NaN,301,NaN,0.15,0.07,0.9,0,100.0
6,AR007,"Beras ketan hitam tumbuk, mentah",KZGPI- 1990,13.7,360.0,8.0,2.3,74.5,1.0,1.5,...,0.28,2.2,0,0,0,0.24,0.10,2.0,0,100.0
7,AR008,"Beras ketan putih tumbuk, mentah",KZGPI- 1990,12.9,361.0,7.4,0.8,78.4,0.4,0.5,...,0.28,2.2,0,0,0,0.28,0.00,1.4,0,100.0
8,AR009,"Beras ladang, mentah",KZGMI-2001,9.8,376.0,7.5,3.8,78.0,5.9,0.9,...,0.10,1.4,0,0,NaN,0.20,0.20,5.1,0,100.0
9,AR010,"Beras menir, mentah",DABM-1964,12.0,362.0,7.7,4.4,73.0,0.2,0.2,...,0.10,0.5,0,0,NaN,0.55,0.00,1.9,0,100.0

4. Info data (tipe & missing):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1146 entries, 0 to 1145
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   KODE             1146 non-null   object
 1   NAMA BAHAN       1146 non-null   object
 2   SUMBER           1146 non-null   object
 3   AIR (g)          1146 non-null   float64
 4   ENERGI (Kal)     1146 non-null   float64
 5   PROTEIN (g)      1145 non-null   float64
 6   LEMAK (g)        1145 non-null   object
 7   KH (g)           1146 non-null   float64
 8   SERAT (g)        967 non-null    object
 9   ABU (g)          1146 non-null   object
 10  KALSIUM (mg)     1129 non-null   object
 11  FOSFOR (mg)      1128 non-null   object
 12  BESI (mg)        1125 non-null   object
 13  NATRIUM (mg)     916 non-null    object
 14  KALIUM (mg)      879 non-null    object
 15  TEMBAGA (mg)     854 non-null    object
 16  SENG (mg)        859 non-null    object
 17  RETINOL (mcg)    580 non-null    object
 18  B-KAR (mcg)      743 non-null    object
 19  KAR-TOTAL (mcg)  650 non-null    object
 20  THIAMIN (mg)     1089 non-null   object
 21  RIBOFLAVIN (mg)  848 non-null    object
 22  NIASIN (mg)      857 non-null    object
 23  VIT-C (mg)       898 non-null    object
 24  BDD (%)          990 non-null    float64
dtypes: float64(5), object(20)
memory usage: 224.0+ KB
None

5. Missing values per kolom:
KODE                 0
NAMA BAHAN           0
SUMBER               0
AIR (g)              0
ENERGI (Kal)         0
PROTEIN (g)          1
LEMAK (g)            1
KH (g)               0
SERAT (g)          179
ABU (g)              0
KALSIUM (mg)        17
FOSFOR (mg)         18
BESI (mg)           21
NATRIUM (mg)       230
KALIUM (mg)        267
TEMBAGA (mg)       292
SENG (mg)          287
RETINOL (mcg)      566
B-KAR (mcg)        403
KAR-TOTAL (mcg)    496
THIAMIN (mg)        57
RIBOFLAVIN (mg)    298
NIASIN (mg)        289
VIT-C (mg)         248
BDD (%)            156
dtype: int64

6. Statistik deskriptif gizi utama:
       ENERGI (Kal)  PROTEIN (g)
count   1146.000000  1145.000000
mean     198.446771     9.673974
std      162.390072    11.507544
min        8.000000     0.000000
25%       74.000000     1.700000
50%      142.500000     4.800000
75%      320.000000    14.500000
max      902.000000    74.300000

7. Bahan dengan protein tertinggi (top 10):
                            NAMA BAHAN  PROTEIN (g)
1001  Dendeng mujahir, goreng, masakan         74.3
957                  Ikan kayu, kering         70.7
984   Ikan Teri, kering, tawar, mentah         68.7
963      Ikan mujahir, dendeng, mentah         68.3
992               Udang kering, mentah         62.6
973             Ikan sale lais, mentah         61.3
980               Ikan, tepung, mentah         60.1
982           Ikan Teri, bubuk, mentah         60.0
988              Rebon, kering, mentah         59.4
953                 Ikan Gabus, kering         58.0

In [ ]:
# Fix tipe data gizi (ubah object ke float, ganti non-numeric jadi 0)
gizi_cols = ['ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'KH (g)', 'SERAT (g)',
             'KALSIUM (mg)', 'FOSFOR (mg)', 'BESI (mg)', 'VIT-C (mg)']

for col in gizi_cols:
    tkpi_df[col] = pd.to_numeric(tkpi_df[col], errors='coerce')  # Non-numeric jadi NaN
    tkpi_df[col] = tkpi_df[col].fillna(0)  # NaN jadi 0

In [ ]:
print("\n8. Bahan dengan besi tertinggi (top 10):")
print(tkpi_df.nlargest(10, 'BESI (mg)')[['NAMA BAHAN', 'BESI (mg)']])

print("\n9. Jumlah varian tempe:")
print(len(tkpi_df[tkpi_df['NAMA BAHAN'].str.contains('tempe', case=False, na=False)]))

print("\n10. Jumlah varian ayam:")
print(len(tkpi_df[tkpi_df['NAMA BAHAN'].str.contains('ayam', case=False, na=False)]))

8. Bahan dengan besi tertinggi (top 10):
                     NAMA BAHAN  BESI (mg)
991   Teripang, dendeng, mentah       96.4
1142                     Terasi       78.5
1124          Daun salam, bubuk       44.1
317              Bungkil kelapa       41.5
349    Oncom kacang tanah pepes       34.4
1076                 Lemak ikan       32.7
1107     Teh melati daun kering       31.6
316        Bungkil kacang tanah       30.7
1104               Sirup pirous       29.5
334               Keripik oncom       27.0

9. Jumlah varian tempe:
20

10. Jumlah varian ayam:
33

In [ ]:
tempe_df = tkpi_df[tkpi_df['NAMA BAHAN'].str.contains('tempe', case=False, na=False)]
tempe_df[['NAMA BAHAN', 'ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'BESI (mg)']]

,NAMA BAHAN,ENERGI (Kal),PROTEIN (g),LEMAK (g),BESI (mg)
335,Keripik tempe,581.0,12.1,40.6,6.9
336,Keripik tempe abadi besar,556.0,15.8,37.1,5.4
337,Keripik tempe abadi murni,542.0,40.3,42.4,5.2
338,Keripik tempe abadi sedang,510.0,12.3,27.9,8.4
339,Keripik tempe abadi telur,529.0,20.8,31.7,5.4
340,Kerupik tempe abadi prima,540.0,16.7,33.9,3.2
365,Tempe bongkrek,119.0,4.4,3.5,2.6
366,Tempe gembus P3G,73.0,5.7,1.3,1.5
367,Tempe gembus yogya,76.0,6.8,0.7,16.5
368,Tempe kacang babi,139.0,12.5,0.8,2.6
369,Tempe kacang belimbing,212.0,17.5,10.0,2.2
370,Tempe kedelai + jagung,143.0,12.0,5.5,6.8
371,"Tempe kedelai murni, goreng",350.0,24.5,26.6,4.9
372,"Tempe kedelai murni, mentah",201.0,20.8,8.8,4.0
373,Tempe koro benguk,141.0,10.2,1.3,2.6
374,Tempe lamtoro,128.0,10.7,0.5,0.6
375,"Tempe lamtoro var, gung dengan kulit",146.0,11.7,2.3,6.8
376,"Tempe lamtoro var, gung tanpa kulit",131.0,18.0,0.8,12.4
377,Tempe pasar,150.0,14.0,7.7,1.5
378,Tempe pasar goreng,336.0,20.0,28.0,3.0

In [ ]:
import pandas as pd

# Filter ayam murni (tanpa bayam & pisang ayam)
ayam_df = tkpi_df[
    tkpi_df['NAMA BAHAN'].str.contains(r'\bayam\b', case=False, regex=True, na=False) &
    ~tkpi_df['NAMA BAHAN'].str.contains(r'\bbayam\b|\bpisang ayam\b', case=False, regex=True, na=False)
].reset_index(drop=True)

print("Jumlah varian ayam (tanpa bayam & pisang ayam):", len(ayam_df))
display(ayam_df[['NAMA BAHAN', 'ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'BESI (mg)']])

Jumlah varian ayam (tanpa bayam & pisang ayam): 25

,NAMA BAHAN,ENERGI (Kal),PROTEIN (g),LEMAK (g),BESI (mg)
0,Mie ayam,102.0,6.2,3.9,1.8
1,"Ayam, daging, segar",298.0,18.2,25.0,1.5
2,"Ayam, dideh/darah, segar",75.0,13.8,1.9,1.3
3,"Ayam, hati, segar",261.0,27.4,16.1,15.8
4,"Ayam, ampela, goreng",270.0,32.3,11.2,4.9
5,"Ayam, usus, goreng",473.0,45.2,26.3,8.4
6,"Ayam goreng church texas, dada",338.0,35.2,20.6,5.6
7,"Ayam goreng church, texas paha",287.0,31.0,15.7,4.1
8,"Ayam goreng church texas, sayap",295.0,34.0,16.0,3.0
9,"Ayam goreng kalasan, paha",275.0,37.4,12.2,5.8
10,"Ayam goreng kentucky, dada",298.0,34.2,16.8,5.5
11,"Ayam goreng Kentucky, paha",286.0,32.1,16.1,6.9
12,"Ayam goreng Kentucky, sayap",297.0,35.9,15.2,4.4
13,Ayam goreng mbok berek dada,295.0,39.2,13.6,5.4
14,"Ayam goreng pasundan, dada",246.0,37.9,9.0,7.5
15,"Ayam goreng pasundan, paha",245.0,33.1,11.4,7.3
16,"Ayam goreng pioneer, dada",295.0,37.4,14.7,6.8
17,"Ayam goreng sukabumi, dada",244.0,36.7,9.2,6.1
18,"Ayam goreng sukabumi, paha",283.0,35.7,14.3,5.4
19,"Ayam taliwang, masakan",264.0,18.2,20.1,2.0
20,"Kalio ayam, masakan",203.0,16.0,13.5,4.2
21,"Telur ayam kampung, segar",174.0,10.8,14.0,4.9
22,"Telur ayam ras, segar",154.0,12.4,10.8,3.0
23,"Telur ayam ras, bagian kuning, segar",355.0,16.3,31.9,7.2
24,"Telur ayam, dadar, masakan",251.0,16.3,19.4,2.5

In [ ]:
import pandas as pd

# Filter ayam murni (tanpa bayam & pisang ayam)
ayam_df = tkpi_df[
    tkpi_df['NAMA BAHAN'].str.contains(r'\bayam\b', case=False, regex=True, na=False) &
    ~tkpi_df['NAMA BAHAN'].str.contains(r'\bbayam\b|\bpisang ayam\b', case=False, regex=True, na=False)
].reset_index(drop=True)

print("Jumlah varian ayam (tanpa bayam & pisang ayam):", len(ayam_df))
display(ayam_df[['NAMA BAHAN', 'ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'BESI (mg)']])

Jumlah varian ayam (tanpa bayam & pisang ayam): 25

,NAMA BAHAN,ENERGI (Kal),PROTEIN (g),LEMAK (g),BESI (mg)
0,Mie ayam,102.0,6.2,3.9,1.8
1,"Ayam, daging, segar",298.0,18.2,25.0,1.5
2,"Ayam, dideh/darah, segar",75.0,13.8,1.9,1.3
3,"Ayam, hati, segar",261.0,27.4,16.1,15.8
4,"Ayam, ampela, goreng",270.0,32.3,11.2,4.9
5,"Ayam, usus, goreng",473.0,45.2,26.3,8.4
6,"Ayam goreng church texas, dada",338.0,35.2,20.6,5.6
7,"Ayam goreng church, texas paha",287.0,31.0,15.7,4.1
8,"Ayam goreng church texas, sayap",295.0,34.0,16.0,3.0
9,"Ayam goreng kalasan, paha",275.0,37.4,12.2,5.8
10,"Ayam goreng kentucky, dada",298.0,34.2,16.8,5.5
11,"Ayam goreng Kentucky, paha",286.0,32.1,16.1,6.9
12,"Ayam goreng Kentucky, sayap",297.0,35.9,15.2,4.4
13,Ayam goreng mbok berek dada,295.0,39.2,13.6,5.4
14,"Ayam goreng pasundan, dada",246.0,37.9,9.0,7.5
15,"Ayam goreng pasundan, paha",245.0,33.1,11.4,7.3
16,"Ayam goreng pioneer, dada",295.0,37.4,14.7,6.8
17,"Ayam goreng sukabumi, dada",244.0,36.7,9.2,6.1
18,"Ayam goreng sukabumi, paha",283.0,35.7,14.3,5.4
19,"Ayam taliwang, masakan",264.0,18.2,20.1,2.0
20,"Kalio ayam, masakan",203.0,16.0,13.5,4.2
21,"Telur ayam kampung, segar",174.0,10.8,14.0,4.9
22,"Telur ayam ras, segar",154.0,12.4,10.8,3.0
23,"Telur ayam ras, bagian kuning, segar",355.0,16.3,31.9,7.2
24,"Telur ayam, dadar, masakan",251.0,16.3,19.4,2.5

In [ ]:
import pandas as pd

# Asumsikan tkpi_df sudah ada dari code sebelumnya
# Jika belum, load ulang
tkpi_df = pd.read_excel(TKPI_PATH, sheet_name="Komposisi Pangan", skiprows=3)
tkpi_df = tkpi_df.dropna(how='all')
tkpi_df.columns = ['KODE','NAMA BAHAN','SUMBER','AIR (g)','ENERGI (Kal)','PROTEIN (g)','LEMAK (g)','KH (g)','SERAT (g)','ABU (g)','KALSIUM (mg)','FOSFOR (mg)','BESI (mg)','NATRIUM (mg)','KALIUM (mg)','TEMBAGA (mg)','SENG (mg)','RETINOL (mcg)','B-KAR (mcg)','KAR-TOTAL (mcg)','THIAMIN (mg)','RIBOFLAVIN (mg)','NIASIN (mg)','VIT-C (mg)','BDD (%)']

# Fix tipe & missing
gizi_cols = ['ENERGI (Kal)', 'PROTEIN (g)', 'LEMAK (g)', 'KH (g)', 'SERAT (g)', 'KALSIUM (mg)', 'FOSFOR (mg)', 'BESI (mg)', 'NATRIUM (mg)', 'VIT-C (mg)', 'KAR-TOTAL (mcg)']
for col in gizi_cols:
    tkpi_df[col] = pd.to_numeric(tkpi_df[col], errors='coerce').fillna(0)

# Hapus baris invalid
tkpi_df = tkpi_df.dropna(subset=['NAMA BAHAN'])
tkpi_df = tkpi_df[tkpi_df['NAMA BAHAN'].str.strip() != "TUNGGAL/SINGLE"]

# Buat narasi & metadata
narasi_list = []
metadata_list = []

for _, row in tkpi_df.iterrows():
    nama = row['NAMA BAHAN'].strip().title()
    kode = row['KODE']
    sumber = row['SUMBER']
    energi = row['ENERGI (Kal)']
    protein = row['PROTEIN (g)']
    lemak = row['LEMAK (g)']
    kh = row['KH (g)']
    serat = row['SERAT (g)']
    besi = row['BESI (mg)']
    kalsium = row['KALSIUM (mg)']
    vit_c = row['VIT-C (mg)']
    vit_a = row['KAR-TOTAL (mcg)']

    # Extra keyword
    extra = ""
    if protein > 30:
        extra += "Sangat tinggi protein, cocok untuk olahraga dan pembentukan otot. "
    elif protein > 15:
        extra += "Tinggi protein. "
    if besi > 10:
        extra += "Sangat kaya zat besi, baik untuk anemia. "
    elif besi > 5:
        extra += "Kaya zat besi. "
    if lemak < 5:
        extra += "Rendah lemak. "
    if energi < 100:
        extra += "Rendah kalori, cocok untuk diet. "
    if serat > 5:
        extra += "Tinggi serat, baik untuk pencernaan. "
    if kalsium > 200:
        extra += "Kaya kalsium, baik untuk tulang dan anak. "
    if vit_c > 50:
        extra += "Kaya vitamin C, baik untuk imun. "

    # Narasi
    narasi = f"Bahan: {nama}\n{extra}\nKandungan gizi per 100 gram:\n- Energi: {energi} kkal\n- Protein: {protein} g\n- Lemak: {lemak} g\n- Karbohidrat: {kh} g\n- Serat: {serat} g\n- Zat Besi: {besi} mg\n- Kalsium: {kalsium} mg\n- Vitamin C: {vit_c} mg\n- Vitamin A: {vit_a} mcg"

    narasi_list.append(narasi)

    # Metadata lengkap (termasuk KODE & SUMBER)
    metadata_list.append({
        "kode": kode,
        "sumber": sumber,
        "nama": nama,
        "kalori": energi,
        "protein": protein,
        "lemak": lemak,
        "karbohidrat": kh,
        "serat": serat,
        "besi": besi,
        "kalsium": kalsium,
        "vit_c": vit_c,
        "vit_a": vit_a
    })

print(f"Narasi TKPI selesai! Total: {len(narasi_list)}")
print("\nContoh narasi pertama:")
print(narasi_list[0])
print("\nContoh metadata pertama:")
print(metadata_list[0])

Narasi TKPI selesai! Total: 1146

Contoh narasi pertama:
Bahan: Beras Giling, Mentah
Rendah lemak.
Kandungan gizi per 100 gram:
- Energi: 357.0 kkal
- Protein: 8.4 g
- Lemak: 1.7 g
- Karbohidrat: 77.1 g
- Serat: 0.2 g
- Zat Besi: 1.8 mg
- Kalsium: 147.0 mg
- Vitamin C: 0.0 mg
- Vitamin A: 0.0 mcg

Contoh metadata pertama:
{'kode': 'AR001', 'sumber': 'KZGMI-2001', 'nama': 'Beras Giling, Mentah', 'kalori': 357.0, 'protein': 8.4, 'lemak': 1.7, 'karbohidrat': 77.1, 'serat': 0.2, 'besi': 1.8, 'kalsium': 147.0, 'vit_c': 0.0, 'vit_a': 0.0}

In [ ]:
import json

# Path folder processed di Drive
PROCESSED_PATH = "/content/drive/MyDrive/skripsian/data/processed"
# Buat folder kalau belum ada
import os
os.makedirs(PROCESSED_PATH, exist_ok=True)

# Simpan narasi
narasi_file = f"{PROCESSED_PATH}/narasi_tkpi.json"
with open(narasi_file, 'w', encoding='utf-8') as f:
    json.dump(narasi_list, f, ensure_ascii=False, indent=4)

# Simpan metadata
metadata_file = f"{PROCESSED_PATH}/metadata_tkpi.json"
with open(metadata_file, 'w', encoding='utf-8') as f:
    json.dump(metadata_list, f, ensure_ascii=False, indent=4)

print("Narasi & metadata TKPI berhasil disimpan di Drive!")
print(f"Narasi: {narasi_file}")
print(f"Metadata: {metadata_file}")
print(f"Total narasi: {len(narasi_list)}")

Narasi & metadata TKPI berhasil disimpan di Drive!
Narasi: /content/drive/MyDrive/skripsian/data/processed/narasi_tkpi.json
Metadata: /content/drive/MyDrive/skripsian/data/processed/metadata_tkpi.json
Total narasi: 1146

### Code Text + Numeric + Hybrid Embedding

In [ ]:
import numpy as np
from sentence_transformers import SentenceTransformer
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import TruncatedSVD
import chromadb

In [ ]:
# 1. Load model text embedding
model = SentenceTransformer('intfloat/multilingual-e5-large')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/690 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/201 [00:00<?, ?B/s]

In [ ]:
# 2. Text embedding (passage prefix untuk optimal retrieval)
text_embeddings = model.encode(['passage: ' + n for n in narasi_list], normalize_embeddings=True)

print("Text embedding selesai! Shape:", text_embeddings.shape)

Text embedding selesai! Shape: (1146, 1024)

In [ ]:
# 3. Numeric embedding
# Kolom numeric (10 kolom prioritas)
numeric_cols = ['kalori', 'protein', 'lemak', 'karbohidrat', 'serat', 'besi', 'kalsium', 'vit_c', 'vit_a', 'natrium_mg']  # adjust kalau ada

# Buat array numeric dari metadata_list
nutrition_data = np.array([
    [
        m['kalori'],
        m['protein'],
        m['lemak'],
        m['karbohidrat'],
        m['serat'],
        m['besi'],
        m['kalsium'],
        m['vit_c'],
        m['vit_a'],
        m.get('natrium_mg', 0)  # kalau ada
    ] for m in metadata_list
])

# Normalisasi & reduce dimensi ke 10
nutrition_scaled = MinMaxScaler().fit_transform(nutrition_data)
nutrition_reduced = TruncatedSVD(n_components=10, random_state=42).fit_transform(nutrition_scaled)

print("Numeric embedding selesai! Shape:", nutrition_reduced.shape)  # (n, 10)

Numeric embedding selesai! Shape: (1146, 10)

In [ ]:
# 4. Hybrid embedding (bobot numeric 1.0 — teks dominan)
hybrid_embeddings = np.hstack([text_embeddings, nutrition_reduced * 1.0])

print("Hybrid embedding selesai! Shape:", hybrid_embeddings.shape)  # (n, 1034)

Hybrid embedding selesai! Shape: (1146, 1034)

In [ ]:
# 5. Ingest ke ChromaDB baru (di folder skripsian)
CHROMA_PATH = "/content/drive/MyDrive/skripsian/chroma_db/chroma_tkpi_full"
client = chromadb.PersistentClient(path=CHROMA_PATH)

try:
    client.delete_collection("tkpi_full")
except:
    pass

collection = client.create_collection("tkpi_full")

collection.add(
    ids=[f"tkpi_{i}" for i in range(len(narasi_list))],
    documents=narasi_list,
    embeddings=hybrid_embeddings.tolist(),
    metadatas=metadata_list
)

print("Ingest ke ChromaDB selesai!")
print(f"Collection 'tkpi_full' siap dengan {len(narasi_list)} bahan dari TKPI 2019")

Ingest ke ChromaDB selesai!
Collection 'tkpi_full' siap dengan 1146 bahan dari TKPI 2019

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np
import chromadb

# Load model embed
model = SentenceTransformer('intfloat/multilingual-e5-large')

# Load collection TKPI full
CHROMA_PATH = "/content/drive/MyDrive/skripsian/chroma_db/chroma_tkpi_full"
client = chromadb.PersistentClient(path=CHROMA_PATH)
collection = client.get_collection("tkpi_full")

# Fungsi test retrieval
def test_retrieval(query, k=5):
    # Query embedding hybrid (bobot numeric 1.0)
    q_embed = model.encode(['query: ' + query], normalize_embeddings=True)
    q_hybrid = np.hstack([q_embed, np.zeros((1, 10)) * 1.0])

    results = collection.query(
        query_embeddings=q_hybrid.tolist(),
        n_results=k,
        include=["documents", "metadatas", "distances"]
    )

    print(f"\nQuery: '{query}'")
    print("-" * 80)
    for i in range(k):
        nama = results['metadatas'][0][i]['nama']
        protein = results['metadatas'][0][i]['protein']
        besi = results['metadatas'][0][i]['besi']
        distance = results['distances'][0][i]
        print(f"Rank {i+1} (distance {distance:.4f}): {nama}")
        print(f"   Protein: {protein} g | Besi: {besi} mg")
        print(f"   Narasi preview: {results['documents'][0][i][:200]}...\n")

# Test berbagai query
queries = [
    "Sangat tinggi protein untuk olahraga",
    "kaya zat besi untuk anemia",
    "rendah kalori untuk diet",
    "tinggi serat untuk pencernaan",
    "dada ayam goreng",
    "hati ayam",
    "tempe gembus",
    "keripik tempe renyah",
    "berapa protein dada ayam goreng",
    "menu sarapan sehat anak"
]

for q in queries:
    test_retrieval(q)

Query: 'Sangat tinggi protein untuk olahraga'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3332): Olah-Olah
   Protein: 2.1 g | Besi: 1.2 mg
   Narasi preview: Bahan: Olah-Olah
Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 9.0 kkal
- Protein: 2.1 g
- Lemak: 6.0 g
- Karbohidrat: 7.1 g
- Serat: 4.4 g
- Zat Besi: 1.2 mg
- Kalsium: 26....

Rank 2 (distance 0.3454): Lontar, Segar
   Protein: 0.4 g | Besi: 0.5 mg
   Narasi preview: Bahan: Lontar, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 27.0 kkal
- Protein: 0.4 g
- Lemak: 0.2 g
- Karbohidrat: 6.0 g
- Serat: 1.6 g
- Zat Besi: 0....

Rank 3 (distance 0.3480): Sawi Putih / Pecai,
 Segar
   Protein: 1.0 g | Besi: 1.1 mg
   Narasi preview: Bahan: Sawi Putih / Pecai,
 Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 9.0 kkal
- Protein: 1.0 g
- Lemak: 0.1 g
- Karbohidrat: 1.7 g
- Serat: 0.8 g
- ...

Rank 4 (distance 0.3493): Lantar, Segar
   Protein: 2.2 g | Besi: 0.4 mg
   Narasi preview: Bahan: Lantar, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 34.0 kkal
- Protein: 2.2 g
- Lemak: 0.3 g
- Karbohidrat: 5.5 g
- Serat: 2.9 g
- Zat Besi: 0....

Rank 5 (distance 0.3504): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...


Query: 'kaya zat besi untuk anemia'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3068): Daun Gelang, Segar
   Protein: 1.3 g | Besi: 11.9 mg
   Narasi preview: Bahan: Daun Gelang, Segar
Sangat kaya zat besi, baik untuk anemia. Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 30.0...

Rank 2 (distance 0.3083): Pepea Oncom Ampas
 Tahu
   Protein: 5.2 g | Besi: 12.5 mg
   Narasi preview: Bahan: Pepea Oncom Ampas
 Tahu
Sangat kaya zat besi, baik untuk anemia. Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi:...

Rank 3 (distance 0.3230): Gudeg, Sayur
   Protein: 3.3 g | Besi: 12.8 mg
   Narasi preview: Bahan: Gudeg, Sayur
Sangat kaya zat besi, baik untuk anemia.
Kandungan gizi per 100 gram:
- Energi: 160.0 kkal
- Protein: 3.3 g
- Lemak: 9.2 g
- Karbohidrat: 16.0 g
- Serat: 2.3 g
- Zat Besi: 12.8 mg...

Rank 4 (distance 0.3383): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 5 (distance 0.3415): Lokan, Segar
   Protein: 11.0 g | Besi: 10.9 mg
   Narasi preview: Bahan: Lokan, Segar
Sangat kaya zat besi, baik untuk anemia. Rendah lemak.
Kandungan gizi per 100 gram:
- Energi: 217.0 kkal
- Protein: 11.0 g
- Lemak: 1.7 g
- Karbohidrat: 5.1 g
- Serat: 0.0 g
- Zat...


Query: 'rendah kalori untuk diet'
--------------------------------------------------------------------------------
Rank 1 (distance 0.2910): Cuka
   Protein: 0.1 g | Besi: 0.5 mg
   Narasi preview: Bahan: Cuka
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 21.0 kkal
- Protein: 0.1 g
- Lemak: 0.1 g
- Karbohidrat: 5.0 g
- Serat: 0.0 g
- Zat Besi: 0.5 mg
- Ka...

Rank 2 (distance 0.2956): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 3 (distance 0.2956): Taoge, Seduh
   Protein: 3.0 g | Besi: 0.5 mg
   Narasi preview: Bahan: Taoge, Seduh
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 28.0 kkal
- Protein: 3.0 g
- Lemak: 0.8 g
- Karbohidrat: 4.0 g
- Serat: 1.0 g
- Zat Besi: 0.5...

Rank 4 (distance 0.2963): Tekwan, Masakan
   Protein: 1.9 g | Besi: 1.0 mg
   Narasi preview: Bahan: Tekwan, Masakan
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 53.0 kkal
- Protein: 1.9 g
- Lemak: 0.9 g
- Karbohidrat: 9.4 g
- Serat: 0.0 g
- Zat Besi: ...

Rank 5 (distance 0.2966): Model, Masakan
   Protein: 2.2 g | Besi: 0.8 mg
   Narasi preview: Bahan: Model, Masakan
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 79.0 kkal
- Protein: 2.2 g
- Lemak: 4.0 g
- Karbohidrat: 8.6 g
- Serat: 0.0 g
- Zat Besi: 0...


Query: 'tinggi serat untuk pencernaan'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3092): Terong Hintalo, Segar
   Protein: 1.9 g | Besi: 1.0 mg
   Narasi preview: Bahan: Terong Hintalo, Segar
Rendah lemak. Rendah kalori, cocok untuk diet. Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 45.0 kkal
- Protein: 1.9 g
- Lemak: 0.8 g
- Kar...

Rank 2 (distance 0.3133): Anyang, Sayur
   Protein: 3.4 g | Besi: 2.9 mg
   Narasi preview: Bahan: Anyang, Sayur
Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 126.0 kkal
- Protein: 3.4 g
- Lemak: 7.9 g
- Karbohidrat: 10.3 g
- Serat: 5.4 g
- Zat Besi: 2.9 mg
- K...

Rank 3 (distance 0.3241): Jamur Kuping, Segar
   Protein: 3.8 g | Besi: 1.7 mg
   Narasi preview: Bahan: Jamur Kuping, Segar
Rendah lemak. Rendah kalori, cocok untuk diet. Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 21.0 kkal
- Protein: 3.8 g
- Lemak: 0.6 g
- Karbo...

Rank 4 (distance 0.3257): Rebung, Segar
   Protein: 0.8 g | Besi: 0.5 mg
   Narasi preview: Bahan: Rebung, Segar
Rendah lemak. Rendah kalori, cocok untuk diet. Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 25.0 kkal
- Protein: 0.8 g
- Lemak: 0.1 g
- Karbohidrat...

Rank 5 (distance 0.3281): Kalakai, Segar
   Protein: 2.4 g | Besi: 1.1 mg
   Narasi preview: Bahan: Kalakai, Segar
Rendah lemak. Rendah kalori, cocok untuk diet. Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 38.0 kkal
- Protein: 2.4 g
- Lemak: 0.2 g
- Karbohidra...


Query: 'dada ayam goreng'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3896): Ayam, Dideh/Darah,
 Segar
   Protein: 13.8 g | Besi: 1.3 mg
   Narasi preview: Bahan: Ayam, Dideh/Darah,
 Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 75.0 kkal
- Protein: 13.8 g
- Lemak: 1.9 g
- Karbohidrat: 0.7 g
- Serat: 0.0 g
-...

Rank 2 (distance 0.3929): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 3 (distance 0.4057): Telur Aayam Ras,
 Bagian Putih, Segar
   Protein: 10.8 g | Besi: 0.2 mg
   Narasi preview: Bahan: Telur Aayam Ras,
 Bagian Putih, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 50.0 kkal
- Protein: 10.8 g
- Lemak: 0.0 g
- Karbohidrat: 0.8 g
- Se...

Rank 4 (distance 0.4086): Susu Kuda, Segar
   Protein: 2.0 g | Besi: 0.0 mg
   Narasi preview: Bahan: Susu Kuda, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 40.0 kkal
- Protein: 2.0 g
- Lemak: 1.1 g
- Karbohidrat: 5.4 g
- Serat: 0.0 g
- Zat Besi:...

Rank 5 (distance 0.4113): Olah-Olah
   Protein: 2.1 g | Besi: 1.2 mg
   Narasi preview: Bahan: Olah-Olah
Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 9.0 kkal
- Protein: 2.1 g
- Lemak: 6.0 g
- Karbohidrat: 7.1 g
- Serat: 4.4 g
- Zat Besi: 1.2 mg
- Kalsium: 26....


Query: 'hati ayam'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3985): Ayam, Dideh/Darah,
 Segar
   Protein: 13.8 g | Besi: 1.3 mg
   Narasi preview: Bahan: Ayam, Dideh/Darah,
 Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 75.0 kkal
- Protein: 13.8 g
- Lemak: 1.9 g
- Karbohidrat: 0.7 g
- Serat: 0.0 g
-...

Rank 2 (distance 0.4023): Telur Aayam Ras,
 Bagian Putih, Segar
   Protein: 10.8 g | Besi: 0.2 mg
   Narasi preview: Bahan: Telur Aayam Ras,
 Bagian Putih, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 50.0 kkal
- Protein: 10.8 g
- Lemak: 0.0 g
- Karbohidrat: 0.8 g
- Se...

Rank 3 (distance 0.4087): Mie Ayam
   Protein: 6.2 g | Besi: 1.8 mg
   Narasi preview: Bahan: Mie Ayam
Rendah lemak. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 102.0 kkal
- Protein: 6.2 g
- Lemak: 3.9 g
- Karbohidrat: 10.5 g
- Serat: 0.0 g
- Zat Be...

Rank 4 (distance 0.4107): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 5 (distance 0.4281): Ketimun Krai, Segar
   Protein: 0.5 g | Besi: 1.0 mg
   Narasi preview: Bahan: Ketimun Krai, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 10.0 kkal
- Protein: 0.5 g
- Lemak: 0.2 g
- Karbohidrat: 2.0 g
- Serat: 0.6 g
- Zat Be...


Query: 'tempe gembus'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3742): Tempe Gembus P3G
   Protein: 5.7 g | Besi: 1.5 mg
   Narasi preview: Bahan: Tempe Gembus P3G
Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 73.0 kkal
- Protein: 5.7 g
- Lemak: 1.3 g
- Kar...

Rank 2 (distance 0.4049): Tempe Gembus Yogya
   Protein: 6.8 g | Besi: 16.5 mg
   Narasi preview: Bahan: Tempe Gembus Yogya
Sangat kaya zat besi, baik untuk anemia. Rendah lemak. Rendah kalori, cocok untuk diet. Tinggi serat, baik untuk pencernaan.
Kandungan gizi per 100 gram:
- Energi: 76.0 kkal...

Rank 3 (distance 0.4351): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 4 (distance 0.4688): Tempe Kedelai +
 Jagung
   Protein: 12.0 g | Besi: 6.8 mg
   Narasi preview: Bahan: Tempe Kedelai +
 Jagung
Kaya zat besi.
Kandungan gizi per 100 gram:
- Energi: 143.0 kkal
- Protein: 12.0 g
- Lemak: 5.5 g
- Karbohidrat: 11.4 g
- Serat: 1.9 g
- Zat Besi: 6.8 mg
- Kalsium: 155...

Rank 5 (distance 0.4696): Batatas Gembili, Segar
   Protein: 1.1 g | Besi: 0.2 mg
   Narasi preview: Bahan: Batatas Gembili, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 76.0 kkal
- Protein: 1.1 g
- Lemak: 0.9 g
- Karbohidrat: 16.0 g
- Serat: 4.2 g
- Za...


Query: 'keripik tempe renyah'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3473): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 2 (distance 0.3786): Taoge, Seduh
   Protein: 3.0 g | Besi: 0.5 mg
   Narasi preview: Bahan: Taoge, Seduh
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 28.0 kkal
- Protein: 3.0 g
- Lemak: 0.8 g
- Karbohidrat: 4.0 g
- Serat: 1.0 g
- Zat Besi: 0.5...

Rank 3 (distance 0.3786): Tempe Gembus P3G
   Protein: 5.7 g | Besi: 1.5 mg
   Narasi preview: Bahan: Tempe Gembus P3G
Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 73.0 kkal
- Protein: 5.7 g
- Lemak: 1.3 g
- Kar...

Rank 4 (distance 0.3873): Tekokak, Segar
   Protein: 2.0 g | Besi: 2.0 mg
   Narasi preview: Bahan: Tekokak, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 34.0 kkal
- Protein: 2.0 g
- Lemak: 0.1 g
- Karbohidrat: 7.9 g
- Serat: 4.9 g
- Zat Besi: 2...

Rank 5 (distance 0.3884): Terung Panjang,
 Kukus
   Protein: 1.8 g | Besi: 0.5 mg
   Narasi preview: Bahan: Terung Panjang,
 Kukus
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 23.0 kkal
- Protein: 1.8 g
- Lemak: 0.1 g
- Karbohidrat: 4.9 g
- Serat: 0.4 g
- Zat...


Query: 'berapa protein dada ayam goreng'
--------------------------------------------------------------------------------
Rank 1 (distance 0.2989): Ayam, Dideh/Darah,
 Segar
   Protein: 13.8 g | Besi: 1.3 mg
   Narasi preview: Bahan: Ayam, Dideh/Darah,
 Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 75.0 kkal
- Protein: 13.8 g
- Lemak: 1.9 g
- Karbohidrat: 0.7 g
- Serat: 0.0 g
-...

Rank 2 (distance 0.3042): Sop Kambing,
 Masakan
   Protein: 5.5 g | Besi: 1.6 mg
   Narasi preview: Bahan: Sop Kambing,
 Masakan
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 34.0 kkal
- Protein: 5.5 g
- Lemak: 0.8 g
- Karbohidrat: 1.1 g
- Serat: 0.0 g
- Zat ...

Rank 3 (distance 0.3135): Lema/ Rebung Asam
   Protein: 1.0 g | Besi: 2.9 mg
   Narasi preview: Bahan: Lema/ Rebung Asam
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 15.0 kkal
- Protein: 1.0 g
- Lemak: 0.4 g
- Karbohidrat: 1.9 g
- Serat: 0.0 g
- Zat Besi...

Rank 4 (distance 0.3155): Sop Daging Sapi,
 Masakan
   Protein: 5.8 g | Besi: 2.2 mg
   Narasi preview: Bahan: Sop Daging Sapi,
 Masakan
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 49.0 kkal
- Protein: 5.8 g
- Lemak: 0.5 g
- Karbohidrat: 5.3 g
- Serat: 0.0 g
- ...

Rank 5 (distance 0.3168): Telur Aayam Ras,
 Bagian Putih, Segar
   Protein: 10.8 g | Besi: 0.2 mg
   Narasi preview: Bahan: Telur Aayam Ras,
 Bagian Putih, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 50.0 kkal
- Protein: 10.8 g
- Lemak: 0.0 g
- Karbohidrat: 0.8 g
- Se...


Query: 'menu sarapan sehat anak'
--------------------------------------------------------------------------------
Rank 1 (distance 0.3579): Rawon, Masakan
   Protein: 5.4 g | Besi: 3.3 mg
   Narasi preview: Bahan: Rawon, Masakan
Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 60.0 kkal
- Protein: 5.4 g
- Lemak: 2.5 g
- Karbo...

Rank 2 (distance 0.3622): Soto Kudus, Masakan
   Protein: 2.6 g | Besi: 1.7 mg
   Narasi preview: Bahan: Soto Kudus, Masakan
Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 38.0 kkal
- Protein: 2.6 g
- Lemak: 2.3 g
- ...

Rank 3 (distance 0.3629): Daun Singkong
 Ampenan, Segar
   Protein: 6.2 g | Besi: 2.7 mg
   Narasi preview: Bahan: Daun Singkong
 Ampenan, Segar
Rendah lemak. Rendah kalori, cocok untuk diet. Kaya kalsium, baik untuk tulang dan anak.
Kandungan gizi per 100 gram:
- Energi: 50.0 kkal
- Protein: 6.2 g
- Lemak...

Rank 4 (distance 0.3646): Kelapa Muda, Air,
 Segar
   Protein: 0.2 g | Besi: 0.2 mg
   Narasi preview: Bahan: Kelapa Muda, Air,
 Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 17.0 kkal
- Protein: 0.2 g
- Lemak: 0.1 g
- Karbohidrat: 3.8 g
- Serat: 0.0 g
- Z...

Rank 5 (distance 0.3660): Lontar, Segar
   Protein: 0.4 g | Besi: 0.5 mg
   Narasi preview: Bahan: Lontar, Segar
Rendah lemak. Rendah kalori, cocok untuk diet.
Kandungan gizi per 100 gram:
- Energi: 27.0 kkal
- Protein: 0.4 g
- Lemak: 0.2 g
- Karbohidrat: 6.0 g
- Serat: 1.6 g
- Zat Besi: 0....

### Build ulang Re-Ingest

In [ ]:
from sentence_transformers import SentenceTransformer
import chromadb

# Load model
model = SentenceTransformer('intfloat/multilingual-e5-large')

# Embedding hanya teks (dengan prefix passage untuk optimal)
print("Generating embeddings...")
text_embeddings = model.encode(['passage: ' + n for n in narasi_list],
                               normalize_embeddings=True,
                               show_progress_bar=True)

# Path ChromaDB
CHROMA_PATH = "/content/drive/MyDrive/skripsian/chroma_db/chroma_tkpi_full"

# Buat client baru
client = chromadb.PersistentClient(path=CHROMA_PATH)

# Hapus collection lama jika masih ada (safety)
try:
    client.delete_collection("tkpi_full")
except:
    pass

# Buat collection baru
collection = client.create_collection(name="tkpi_full")

# Ingest dengan pure text embedding
print("Ingesting to ChromaDB...")
collection.add(
    ids=[f"tkpi_{i}" for i in range(len(narasi_list))],
    documents=narasi_list,
    embeddings=text_embeddings.tolist(),   # 1024 dim saja
    metadatas=metadata_list
)

print("Ingest ulang SELESAI!")
print(f"Total item: {collection.count()}")
print(f"Dimensi embedding: {len(text_embeddings[0])}")  # Harusnya 1024

Generating embeddings...

Batches:   0%|          | 0/36 [00:00<?, ?it/s]

Ingesting to ChromaDB...
Ingest ulang SELESAI!
Total item: 1146
Dimensi embedding: 1024

In [ ]:
import re

def parse_query(query):
    query_lower = query.lower()

    if re.search(r'(tinggi|sangat tinggi|kaya|banyak|penambah)', query_lower):
        if 'protein' in query_lower:
            return {'col': 'protein', 'order': 'desc'}
        elif any(x in query_lower for x in ['zat besi', 'besi', 'iron', 'darah']):
            return {'col': 'besi', 'order': 'desc'}
        elif 'serat' in query_lower:
            return {'col': 'serat', 'order': 'desc'}
        elif any(x in query_lower for x in ['kalsium', 'tulang']):
            return {'col': 'kalsium', 'order': 'desc'}
        elif any(x in query_lower for x in ['vitamin c', 'vit c', 'daya tahan']):
            return {'col': 'vit_c', 'order': 'desc'}
        elif any(x in query_lower for x in ['vitamin a', 'vit a', 'mata']):
            return {'col': 'vit_a', 'order': 'desc'}
        elif any(x in query_lower for x in ['energi', 'kalori tinggi']):
            return {'col': 'kalori', 'order': 'desc'}

    elif re.search(r'(rendah|kecil|sedikit|diet)', query_lower):
        if 'kalori' in query_lower:
            return {'col': 'kalori', 'order': 'asc'}
        elif 'lemak' in query_lower:
            return {'col': 'lemak', 'order': 'asc'}
        elif any(x in query_lower for x in ['natrium', 'garam']):
            return {'col': 'natrium_mg', 'order': 'asc'}
        elif any(x in query_lower for x in ['karbohidrat', 'diabetes']):
            return {'col': 'karbohidrat', 'order': 'asc'}

    return None

    # --- 2. Intent Detection (rule-based) ---
INTENT_NUTRITION = 'nutrition'
INTENT_FOOD_NAME = 'food_name'
INTENT_MEAL_CONTEXT = 'meal_context'

def detect_intent(query):
    query_lower = query.lower()

    # Nutrition intent
    nutrition_keywords = ['protein', 'zat besi', 'besi', 'kalori', 'serat', 'kalsium', 'vitamin', 'vit', 'energi', 'lemak', 'natrium', 'karbohidrat', 'kaya', 'tinggi', 'rendah']
    if any(k in query_lower for k in nutrition_keywords):
        return INTENT_NUTRITION

    # Meal / context intent
    context_keywords = ['sarapan', 'makan malam', 'cemilan', 'ngemil', 'diet', 'diabetes', 'hamil', 'anak', 'sekolah', 'olahraga', 'atlet', 'penambah darah', 'mengenyangkan', 'menu']
    if any(k in query_lower for k in context_keywords):
        return INTENT_MEAL_CONTEXT

    # Default: food name intent
    return INTENT_FOOD_NAME

# --- 3. Hybrid Retrieval dengan Intent Routing ---
def hybrid_retrieval(query, k=5, candidate_k=50):
    intent = detect_intent(query)

    # Embedding query
    q_embed = model.encode(['query: ' + query], normalize_embeddings=True)

    # Semantic retrieval top candidates
    results = collection.query(
        query_embeddings=q_embed.tolist(),
        n_results=candidate_k,
        include=["documents", "metadatas", "distances"]
    )

    candidates = results['metadatas'][0] if results['metadatas'] else []
    distances = results['distances'][0] if results['distances'] else [0] * len(candidates)

    # Mapping index untuk distance
    def get_distance(idx):
        try:
            return distances[candidates.index(results['metadatas'][0][idx])]
        except:
            return 1.0

    # Routing berdasarkan intent
    if intent == INTENT_NUTRITION:
        criteria = parse_query(query)
        if criteria and candidates:
            sorted_cands = sorted(
                candidates,
                key=lambda x: float(x.get(criteria['col'], 0) or 0),
                reverse=(criteria['order'] == 'desc')
            )
            return sorted_cands[:k]
        else:
            return candidates[:k]  # fallback semantic

    elif intent == INTENT_FOOD_NAME:
        # Extract kata kunci utama (protein source)
        main_ingredients = re.findall(r'\b(ayam|tempe|ikan|daging|sapi|kambing|tuna|telur|tahu|kacang)\b', query_lower := query.lower())

        if main_ingredients:
            # Boost item yang punya kata utama di nama
            sorted_cands = sorted(
                candidates,
                key=lambda x: (
                    -sum(ing in x['nama'].lower() for ing in main_ingredients),  # lebih banyak match = lebih tinggi
                    get_distance(candidates.index(x))  # tie-breaker: semantic distance
                )
            )
        else:
            # Pure semantic
            sorted_cands = sorted(candidates, key=lambda x: get_distance(candidates.index(x)))

        return sorted_cands[:k]

    elif intent == INTENT_MEAL_CONTEXT:
        # Heuristic filter: hindari makanan ekstrem untuk konteks anak/sarapan/diet
        exclude_words = ['mentah', 'kering', 'bubuk', 'dendeng', 'teripang', 'terasi']
        filtered = [c for c in candidates if not any(word in c['nama'].lower() for word in exclude_words)]

        if not filtered:  # kalau terlalu ketat, fallback
            filtered = candidates

        # Jika ada kriteria nutrisi, rerank
        criteria = parse_query(query)
        if criteria:
            sorted_cands = sorted(
                filtered,
                key=lambda x: float(x.get(criteria['col'], 0) or 0),
                reverse=(criteria['order'] == 'desc')
            )
        else:
            sorted_cands = sorted(filtered, key=lambda x: get_distance(candidates.index(x)))

        return sorted_cands[:k]

    return candidates[:k]
# --- 4. Test 50 Query ---
test_queries = [
    "Berapa kandungan gizi lengkap beras giling mentah per 100 gram?",
    "Apa saja zat gizi dalam beras hitam mentah, termasuk energi dan protein?",
    "Kandungan kalori, protein, dan lemak di beras jagung kuning kering mentah per 100 gram?",
    "Berapa besi dan kalsium dalam beras ketan hitam tumbuk mentah?",
    "Kandungan gizi lengkap tempe kedelai murni goreng per 100 gram?",
    "Apa protein dan serat di tempe pasar goreng?",
    "Kandungan energi, lemak, dan karbohidrat di tempe lamtoro?",
    "Berapa vitamin A dan besi dalam ayam goreng Kentucky dada?",
    "Kandungan gizi lengkap ayam goreng Church Texas dada per 100 gram?",
    "Apa kalori dan protein di ayam hati segar?",
    "Kandungan besi, kalsium, dan vitamin C di ikan mujahir segar?",
    "Berapa protein dan lemak di ikan teri kering tawar mentah?",
    "Kandungan gizi lengkap ikan sale lais mentah per 100 gram?",
    "Apa energi dan serat di jagung muda kuning mentah?",
    "Kandungan kalori, protein, dan besi di kacang kedelai goreng?",
    "Berapa kalsium dan vitamin A di susu bubuk?",
    "Kandungan gizi lengkap kecap per 100 gram?",
    "Apa lemak dan natrium di terasi?",
    "Kandungan besi dan protein di oncom kacang tanah pepes?",
    "Berapa kalori dan serat di rebung segar?",
    "Kandungan gizi lengkap daun singkong segar per 100 gram?",
    "Apa protein dan vitamin C di jambu biji segar?",
    "Kandungan energi, lemak, dan kalsium di keju?",
    "Berapa besi dan vitamin A di hati babi segar?",
    "Kandungan gizi lengkap nasi per 100 gram?",
    "Apa serat dan karbohidrat di beras merah nasi?",
    "Kandungan protein, besi, dan kalium di kacang bogor kering?",
    "Berapa kalori dan lemak di martabak india?",
    "Kandungan gizi lengkap mie ayam per 100 gram?",
    "Apa vitamin C dan besi di cabai merah segar?",
    "Kandungan energi, protein, dan serat di durian segar?",
    "Berapa kalsium dan besi di ikan bandeng presto masakan?",
    "Kandungan gizi lengkap sop buntut masakan per 100 gram?",
    "Apa lemak dan natrium di saos tomat?",
    "Kandungan protein dan vitamin A di daun mangkokan segar?",
    "Berapa besi dan serat di kacang endel biji kering?",
    "Kandungan gizi lengkap petis udang pasta per 100 gram?",
    "Apa kalori dan kalsium di air kelapa muda segar?",
    "Kandungan energi, lemak, dan karbohidrat di biskuit?",
    "Berapa protein dan besi di daging sapi kornet?",
    "Kandungan gizi lengkap gado-gado per 100 gram?",
    "Apa serat dan vitamin C di salak medan segar?",
    "Kandungan besi, kalsium, dan vitamin A di genjer segar?",
    "Berapa kalori dan protein di bakwan?",
    "Kandungan gizi lengkap rendang sapi masakan per 100 gram?",
    "Apa lemak dan natrium di bekasam?",
    "Kandungan energi, serat, dan besi di cabai merah kering?",
    "Berapa vitamin A dan kalsium di andaliman segar?",
    "Kandungan gizi lengkap kwaci per 100 gram?",
    "Apa protein, besi, dan kalium di wijen mentah?"
]

print(f"Memulai pengujian {len(test_queries)} query dengan Intent Detection + Routing...\n")
print("="*120)

for idx, query in enumerate(test_queries, 1):
    intent = detect_intent(query)
    print(f"{idx:2}. QUERY: \"{query}\"")
    print(f"     → Detected Intent: {intent.upper()}")
    print("-" * 100)

    results = hybrid_retrieval(query, k=5)

    for rank, item in enumerate(results, 1):
        nama = item['nama']
        kalori = item.get('kalori', 'N/A')
        protein = item.get('protein', 'N/A')
        lemak = item.get('lemak', 'N/A')
        karbohidrat = item.get('karbohidrat', 'N/A')
        serat = item.get('serat', 'N/A')
        kalsium = item.get('kalsium', 'N/A')
        besi = item.get('besi', 'N/A')
        vit_a = item.get('vit_a', 'N/A')
        vit_c = item.get('vit_c', 'N/A')

        print(f"   {rank}. {nama}")
        print(f"      Kalori: {kalori}kkal |  Protein: {protein}g | Lemak: {lemak}g | Karbohidrat: {karbohidrat}g | Serat: {serat}g | Kalsium: {kalsium}mg | Besi: {besi}mg | Retinol: {vit_a}mcg | Vit C: {vit_c}mg")

    print("\n")

Memulai pengujian 50 query dengan Intent Detection + Routing...

========================================================================================================================
 1. QUERY: "Berapa kandungan gizi lengkap beras giling mentah per 100 gram?"
     → Detected Intent: FOOD_NAME
----------------------------------------------------------------------------------------------------
   1. Beras Giling, Mentah
      Kalori: 357.0kkal |  Protein: 8.4g | Lemak: 1.7g | Karbohidrat: 77.1g | Serat: 0.2g | Kalsium: 147.0mg | Besi: 1.8mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Beras Giling Var Pelita, Mentah
      Kalori: 369.0kkal |  Protein: 9.5g | Lemak: 1.4g | Karbohidrat: 77.1g | Serat: 0.4g | Kalsium: 68.0mg | Besi: 1.4mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Beras, Tepung, Mentah
      Kalori: 353.0kkal |  Protein: 7.0g | Lemak: 0.5g | Karbohidrat: 80.0g | Serat: 2.4g | Kalsium: 5.0mg | Besi: 0.8mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Beras Menir, Mentah
      Kalori: 362.0kkal |  Protein: 7.7g | Lemak: 4.4g | Karbohidrat: 73.0g | Serat: 0.2g | Kalsium: 22.0mg | Besi: 3.7mg | Retinol: 0.0mcg | Vit C: 0.0mg
   5. Beras Tumbuk, Mentah
      Kalori: 354.0kkal |  Protein: 7.8g | Lemak: 0.4g | Karbohidrat: 79.9g | Serat: 3.8g | Kalsium: 3.0mg | Besi: 0.6mg | Retinol: 0.0mcg | Vit C: 0.0mg


 2. QUERY: "Apa saja zat gizi dalam beras hitam mentah, termasuk energi dan protein?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Beras Hitam, Mentah
      Kalori: 351.0kkal |  Protein: 8.0g | Lemak: 1.3g | Karbohidrat: 76.9g | Serat: 20.1g | Kalsium: 6.0mg | Besi: 0.1mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Beras Ketan Hitam
Tumbuk, Mentah
      Kalori: 360.0kkal |  Protein: 8.0g | Lemak: 2.3g | Karbohidrat: 74.5g | Serat: 1.0g | Kalsium: 10.0mg | Besi: 6.2mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Beras Tumbuk, Mentah
      Kalori: 354.0kkal |  Protein: 7.8g | Lemak: 0.4g | Karbohidrat: 79.9g | Serat: 3.8g | Kalsium: 3.0mg | Besi: 0.6mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Beras Tumbuk Merah, Mentah
      Kalori: 352.0kkal |  Protein: 7.3g | Lemak: 0.9g | Karbohidrat: 76.2g | Serat: 0.8g | Kalsium: 15.0mg | Besi: 4.2mg | Retinol: 0.0mcg | Vit C: 0.0mg
   5. Beras Menir, Mentah
      Kalori: 362.0kkal |  Protein: 7.7g | Lemak: 4.4g | Karbohidrat: 73.0g | Serat: 0.2g | Kalsium: 22.0mg | Besi: 3.7mg | Retinol: 0.0mcg | Vit C: 0.0mg


 3. QUERY: "Kandungan kalori, protein, dan lemak di beras jagung kuning kering mentah per 100 gram?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Beras Jagung Kuning, Kering, Mentah
      Kalori: 358.0kkal |  Protein: 5.5g | Lemak: 0.1g | Karbohidrat: 82.7g | Serat: 10.0g | Kalsium: 20.0mg | Besi: 1.4mg | Retinol: 0.0mcg | Vit C: 3.0mg
   2. Beras Jagung Putih,
Kering, Mentah
      Kalori: 307.0kkal |  Protein: 4.8g | Lemak: 0.1g | Karbohidrat: 71.8g | Serat: 10.0g | Kalsium: 17.0mg | Besi: 1.2mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Jagung Muda, Kuning, Mentah
      Kalori: 147.0kkal |  Protein: 5.1g | Lemak: 0.7g | Karbohidrat: 31.5g | Serat: 1.3g | Kalsium: 6.0mg | Besi: 1.1mg | Retinol: 261.0mcg | Vit C: 9.0mg
   4. Jagung Kuning, Tepung
      Kalori: 355.0kkal |  Protein: 9.2g | Lemak: 3.9g | Karbohidrat: 73.7g | Serat: 7.2g | Kalsium: 10.0mg | Besi: 2.4mg | Retinol: 510.0mcg | Vit C: 0.0mg
   5. Jagung Kuning Pipil, Kering, Mentah
      Kalori: 366.0kkal |  Protein: 9.8g | Lemak: 7.3g | Karbohidrat: 69.1g | Serat: 2.2g | Kalsium: 30.0mg | Besi: 2.3mg | Retinol: 641.0mcg | Vit C: 3.0mg


 4. QUERY: "Berapa besi dan kalsium dalam beras ketan hitam tumbuk mentah?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Beras Ketan Hitam
Tumbuk, Mentah
      Kalori: 360.0kkal |  Protein: 8.0g | Lemak: 2.3g | Karbohidrat: 74.5g | Serat: 1.0g | Kalsium: 10.0mg | Besi: 6.2mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Beras Ketan Putih
Tumbuk, Mentah
      Kalori: 361.0kkal |  Protein: 7.4g | Lemak: 0.8g | Karbohidrat: 78.4g | Serat: 0.4g | Kalsium: 13.0mg | Besi: 3.4mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Beras Hitam, Mentah
      Kalori: 351.0kkal |  Protein: 8.0g | Lemak: 1.3g | Karbohidrat: 76.9g | Serat: 20.1g | Kalsium: 6.0mg | Besi: 0.1mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Beras Tumbuk Merah, Mentah
      Kalori: 352.0kkal |  Protein: 7.3g | Lemak: 0.9g | Karbohidrat: 76.2g | Serat: 0.8g | Kalsium: 15.0mg | Besi: 4.2mg | Retinol: 0.0mcg | Vit C: 0.0mg
   5. Beras Tumbuk, Mentah
      Kalori: 354.0kkal |  Protein: 7.8g | Lemak: 0.4g | Karbohidrat: 79.9g | Serat: 3.8g | Kalsium: 3.0mg | Besi: 0.6mg | Retinol: 0.0mcg | Vit C: 0.0mg


 5. QUERY: "Kandungan gizi lengkap tempe kedelai murni goreng per 100 gram?"
     → Detected Intent: FOOD_NAME
----------------------------------------------------------------------------------------------------
   1. Tempe Kedelai Murni,
 Mentah
      Kalori: 201.0kkal |  Protein: 20.8g | Lemak: 8.8g | Karbohidrat: 13.5g | Serat: 1.4g | Kalsium: 155.0mg | Besi: 4.0mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Tempe Kedelai Murni,
 Goreng
      Kalori: 350.0kkal |  Protein: 24.5g | Lemak: 26.6g | Karbohidrat: 10.4g | Serat: 4.2g | Kalsium: 202.0mg | Besi: 4.9mg | Retinol: 78.0mcg | Vit C: 0.0mg
   3. Tempe Kedelai +
 Jagung
      Kalori: 143.0kkal |  Protein: 12.0g | Lemak: 5.5g | Karbohidrat: 11.4g | Serat: 1.9g | Kalsium: 155.0mg | Besi: 6.8mg | Retinol: 1320.0mcg | Vit C: 0.0mg
   4. Tempe Pasar Goreng
      Kalori: 336.0kkal |  Protein: 20.0g | Lemak: 28.0g | Karbohidrat: 7.8g | Serat: 3.4g | Kalsium: 156.0mg | Besi: 3.0mg | Retinol: 10.0mcg | Vit C: 0.0mg
   5. Tempe Kacang Babi
      Kalori: 139.0kkal |  Protein: 12.5g | Lemak: 0.8g | Karbohidrat: 21.9g | Serat: 1.8g | Kalsium: 68.0mg | Besi: 2.6mg | Retinol: 20.0mcg | Vit C: 0.0mg


 6. QUERY: "Apa protein dan serat di tempe pasar goreng?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Tempe Pasar Goreng
      Kalori: 336.0kkal |  Protein: 20.0g | Lemak: 28.0g | Karbohidrat: 7.8g | Serat: 3.4g | Kalsium: 156.0mg | Besi: 3.0mg | Retinol: 10.0mcg | Vit C: 0.0mg
   2. Tempe Pasar
      Kalori: 150.0kkal |  Protein: 14.0g | Lemak: 7.7g | Karbohidrat: 9.1g | Serat: 1.4g | Kalsium: 517.0mg | Besi: 1.5mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Tempe Kedelai Murni,
 Goreng
      Kalori: 350.0kkal |  Protein: 24.5g | Lemak: 26.6g | Karbohidrat: 10.4g | Serat: 4.2g | Kalsium: 202.0mg | Besi: 4.9mg | Retinol: 78.0mcg | Vit C: 0.0mg
   4. Tempe Lamtoro Var,
 Gung Dengan Kulit
      Kalori: 146.0kkal |  Protein: 11.7g | Lemak: 2.3g | Karbohidrat: 19.6g | Serat: 7.6g | Kalsium: 128.0mg | Besi: 6.8mg | Retinol: 1370.0mcg | Vit C: 0.0mg
   5. Tempe Kedelai Murni,
 Mentah
      Kalori: 201.0kkal |  Protein: 20.8g | Lemak: 8.8g | Karbohidrat: 13.5g | Serat: 1.4g | Kalsium: 155.0mg | Besi: 4.0mg | Retinol: 0.0mcg | Vit C: 0.0mg


 7. QUERY: "Kandungan energi, lemak, dan karbohidrat di tempe lamtoro?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Tempe Lamtoro Var,
 Gung Dengan Kulit
      Kalori: 146.0kkal |  Protein: 11.7g | Lemak: 2.3g | Karbohidrat: 19.6g | Serat: 7.6g | Kalsium: 128.0mg | Besi: 6.8mg | Retinol: 1370.0mcg | Vit C: 0.0mg
   2. Tempe Lamtoro
      Kalori: 128.0kkal |  Protein: 10.7g | Lemak: 0.5g | Karbohidrat: 21.3g | Serat: 7.1g | Kalsium: 203.0mg | Besi: 0.6mg | Retinol: 121.0mcg | Vit C: 2.0mg
   3. Tempe Lamtoro Var,
 Gung Tanpa Kulit
      Kalori: 131.0kkal |  Protein: 18.0g | Lemak: 0.8g | Karbohidrat: 13.0g | Serat: 1.3g | Kalsium: 95.0mg | Besi: 12.4mg | Retinol: 5900.0mcg | Vit C: 0.0mg
   4. Lamtoro Biji, Tua,
 Segar
      Kalori: 148.0kkal |  Protein: 10.6g | Lemak: 0.5g | Karbohidrat: 26.2g | Serat: 17.0g | Kalsium: 155.0mg | Besi: 2.2mg | Retinol: 416.0mcg | Vit C: 20.0mg
   5. Lamtoro Biji, Muda,
 Segar
      Kalori: 85.0kkal |  Protein: 5.7g | Lemak: 0.3g | Karbohidrat: 15.4g | Serat: 10.8g | Kalsium: 180.0mg | Besi: 2.7mg | Retinol: 423.0mcg | Vit C: 15.0mg


 8. QUERY: "Berapa vitamin A dan besi dalam ayam goreng Kentucky dada?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Ayam Goreng
 Kentucky, Dada
      Kalori: 298.0kkal |  Protein: 34.2g | Lemak: 16.8g | Karbohidrat: 0.1g | Serat: 0.0g | Kalsium: 90.0mg | Besi: 5.5mg | Retinol: 50.0mcg | Vit C: 0.0mg
   2. Ayam Goreng
 Kentucky, Paha
      Kalori: 286.0kkal |  Protein: 32.1g | Lemak: 16.1g | Karbohidrat: 1.1g | Serat: 0.0g | Kalsium: 89.0mg | Besi: 6.9mg | Retinol: 20.0mcg | Vit C: 0.0mg
   3. Ayam Goreng
 Kentucky,Sayap
      Kalori: 297.0kkal |  Protein: 35.9g | Lemak: 15.2g | Karbohidrat: 1.6g | Serat: 0.0g | Kalsium: 103.0mg | Besi: 4.4mg | Retinol: 70.0mcg | Vit C: 0.0mg
   4. Ayam Goreng Church
 Texas, Dada
      Kalori: 338.0kkal |  Protein: 35.2g | Lemak: 20.6g | Karbohidrat: 0.4g | Serat: 0.0g | Kalsium: 79.0mg | Besi: 5.6mg | Retinol: 80.0mcg | Vit C: 0.0mg
   5. Ayam Goreng
 Sukabumi, Dada
      Kalori: 244.0kkal |  Protein: 36.7g | Lemak: 9.2g | Karbohidrat: 1.0g | Serat: 0.0g | Kalsium: 81.0mg | Besi: 6.1mg | Retinol: 80.0mcg | Vit C: 0.0mg


 9. QUERY: "Kandungan gizi lengkap ayam goreng Church Texas dada per 100 gram?"
     → Detected Intent: FOOD_NAME
----------------------------------------------------------------------------------------------------
   1. Ayam Goreng Church
 Texas, Dada
      Kalori: 338.0kkal |  Protein: 35.2g | Lemak: 20.6g | Karbohidrat: 0.4g | Serat: 0.0g | Kalsium: 79.0mg | Besi: 5.6mg | Retinol: 80.0mcg | Vit C: 0.0mg
   2. Ayam Goreng Church
 Texas, Sayap
      Kalori: 295.0kkal |  Protein: 34.0g | Lemak: 16.0g | Karbohidrat: 1.5g | Serat: 0.0g | Kalsium: 81.0mg | Besi: 3.0mg | Retinol: 50.0mcg | Vit C: 0.0mg
   3. Ayam Goreng
 Church,Texas Paha
      Kalori: 287.0kkal |  Protein: 31.0g | Lemak: 15.7g | Karbohidrat: 1.7g | Serat: 0.0g | Kalsium: 99.0mg | Besi: 4.1mg | Retinol: 30.0mcg | Vit C: 0.0mg
   4. Ayam Goreng
 Kentucky, Dada
      Kalori: 298.0kkal |  Protein: 34.2g | Lemak: 16.8g | Karbohidrat: 0.1g | Serat: 0.0g | Kalsium: 90.0mg | Besi: 5.5mg | Retinol: 50.0mcg | Vit C: 0.0mg
   5. Ayam, Daging, Segar
      Kalori: 298.0kkal |  Protein: 18.2g | Lemak: 25.0g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 14.0mg | Besi: 1.5mg | Retinol: 0.0mcg | Vit C: 0.0mg


10. QUERY: "Apa kalori dan protein di ayam hati segar?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Ayam, Hati, Segar
      Kalori: 261.0kkal |  Protein: 27.4g | Lemak: 16.1g | Karbohidrat: 1.6g | Serat: 0.0g | Kalsium: 118.0mg | Besi: 15.8mg | Retinol: 28000.0mcg | Vit C: 0.0mg
   2. Ayam, Daging, Segar
      Kalori: 298.0kkal |  Protein: 18.2g | Lemak: 25.0g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 14.0mg | Besi: 1.5mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Ayam, Dideh/Darah,
 Segar
      Kalori: 75.0kkal |  Protein: 13.8g | Lemak: 1.9g | Karbohidrat: 0.7g | Serat: 0.0g | Kalsium: 15.0mg | Besi: 1.3mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Babi, Hati, Segar
      Kalori: 129.0kkal |  Protein: 19.7g | Lemak: 4.8g | Karbohidrat: 1.7g | Serat: 0.0g | Kalsium: 10.0mg | Besi: 18.0mg | Retinol: 0.0mcg | Vit C: 23.0mg
   5. Sapi, Hati, Sosis
 (Liverworst)
      Kalori: 274.0kkal |  Protein: 16.0g | Lemak: 22.0g | Karbohidrat: 3.0g | Serat: 2.3g | Kalsium: 20.0mg | Besi: 4.0mg | Retinol: 0.0mcg | Vit C: 0.0mg


11. QUERY: "Kandungan besi, kalsium, dan vitamin C di ikan mujahir segar?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Ikan Mujahir, Segar
      Kalori: 89.0kkal |  Protein: 18.7g | Lemak: 1.0g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 96.0mg | Besi: 1.5mg | Retinol: 5.0mcg | Vit C: 0.0mg
   2. Ikan Mujahir Pepes
      Kalori: 121.0kkal |  Protein: 21.7g | Lemak: 2.8g | Karbohidrat: 0.8g | Serat: 0.0g | Kalsium: 83.0mg | Besi: 1.6mg | Retinol: 6.0mcg | Vit C: 0.0mg
   3. Ikan Mujahir,
 Dendeng, Mentah
      Kalori: 582.0kkal |  Protein: 68.3g | Lemak: 15.2g | Karbohidrat: 37.2g | Serat: 0.0g | Kalsium: 3258.0mg | Besi: 4.3mg | Retinol: 20.0mcg | Vit C: 0.0mg
   4. Ikan Mujahir Goreng
      Kalori: 416.0kkal |  Protein: 46.9g | Lemak: 23.9g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 346.0mg | Besi: 0.9mg | Retinol: 8.0mcg | Vit C: 0.0mg
   5. Mujahir Acar Kuning,
 Masakan
      Kalori: 330.0kkal |  Protein: 17.8g | Lemak: 23.4g | Karbohidrat: 12.1g | Serat: 1.1g | Kalsium: 154.0mg | Besi: 5.3mg | Retinol: 4130.0mcg | Vit C: 0.0mg


12. QUERY: "Berapa protein dan lemak di ikan teri kering tawar mentah?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Ikan Teri, Kering,
 Tawar, Mentah
      Kalori: 331.0kkal |  Protein: 68.7g | Lemak: 4.2g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 2381.0mg | Besi: 23.4mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Ikan Teri, Kering,
 Mentah
      Kalori: 170.0kkal |  Protein: 33.4g | Lemak: 3.0g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 1200.0mg | Besi: 3.6mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Ikan Teri Nasi, Kering,
 Mentah
      Kalori: 144.0kkal |  Protein: 32.5g | Lemak: 0.6g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 1000.0mg | Besi: 3.0mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Ikan Teri, Bubuk,
 Mentah
      Kalori: 277.0kkal |  Protein: 60.0g | Lemak: 2.3g | Karbohidrat: 1.8g | Serat: 0.0g | Kalsium: 1209.0mg | Besi: 3.0mg | Retinol: 0.0mcg | Vit C: 0.0mg
   5. Ikan Teri, Segar
      Kalori: 74.0kkal |  Protein: 10.3g | Lemak: 1.4g | Karbohidrat: 4.1g | Serat: 0.0g | Kalsium: 972.0mg | Besi: 3.9mg | Retinol: 28.0mcg | Vit C: 0.0mg


13. QUERY: "Kandungan gizi lengkap ikan sale lais mentah per 100 gram?"
     → Detected Intent: FOOD_NAME
----------------------------------------------------------------------------------------------------
   1. Ikan Sale Lais, Mentah
      Kalori: 415.0kkal |  Protein: 61.3g | Lemak: 17.6g | Karbohidrat: 2.9g | Serat: 0.0g | Kalsium: 258.0mg | Besi: 7.0mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Ikan Lais, Segar
      Kalori: 161.0kkal |  Protein: 11.9g | Lemak: 11.5g | Karbohidrat: 2.4g | Serat: 0.0g | Kalsium: 70.0mg | Besi: 0.0mg | Retinol: 0.0mcg | Vit C: 0.0mg
   3. Ikan Lais Bakar
      Kalori: 147.0kkal |  Protein: 17.5g | Lemak: 6.5g | Karbohidrat: 5.4g | Serat: 0.0g | Kalsium: 54.0mg | Besi: 0.1mg | Retinol: 0.0mcg | Vit C: 0.0mg
   4. Ikan Sale, Mentah
      Kalori: 534.0kkal |  Protein: 40.2g | Lemak: 39.3g | Karbohidrat: 4.9g | Serat: 2.0g | Kalsium: 199.0mg | Besi: 2.7mg | Retinol: 0.0mcg | Vit C: 0.0mg
   5. Ikan Selar Kuning, Cue,
 Mentah
      Kalori: 138.0kkal |  Protein: 27.0g | Lemak: 3.3g | Karbohidrat: 0.0g | Serat: 0.0g | Kalsium: 50.0mg | Besi: 2.0mg | Retinol: 0.0mcg | Vit C: 0.0mg


14. QUERY: "Apa energi dan serat di jagung muda kuning mentah?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Jagung Muda, Kuning, Mentah
      Kalori: 147.0kkal |  Protein: 5.1g | Lemak: 0.7g | Karbohidrat: 31.5g | Serat: 1.3g | Kalsium: 6.0mg | Besi: 1.1mg | Retinol: 261.0mcg | Vit C: 9.0mg
   2. Jagung Muda / Semi,
 Segar
      Kalori: 35.0kkal |  Protein: 2.2g | Lemak: 0.1g | Karbohidrat: 7.4g | Serat: 1.9g | Kalsium: 7.0mg | Besi: 0.5mg | Retinol: 200.0mcg | Vit C: 8.0mg
   3. Jagung Muda, Rebus
      Kalori: 142.0kkal |  Protein: 5.0g | Lemak: 0.7g | Karbohidrat: 30.3g | Serat: 0.8g | Kalsium: 5.0mg | Besi: 0.8mg | Retinol: 225.0mcg | Vit C: 0.0mg
   4. Beras Jagung Kuning, Kering, Mentah
      Kalori: 358.0kkal |  Protein: 5.5g | Lemak: 0.1g | Karbohidrat: 82.7g | Serat: 10.0g | Kalsium: 20.0mg | Besi: 1.4mg | Retinol: 0.0mcg | Vit C: 3.0mg
   5. Jagung Kuning, Tepung
      Kalori: 355.0kkal |  Protein: 9.2g | Lemak: 3.9g | Karbohidrat: 73.7g | Serat: 7.2g | Kalsium: 10.0mg | Besi: 2.4mg | Retinol: 510.0mcg | Vit C: 0.0mg


15. QUERY: "Kandungan kalori, protein, dan besi di kacang kedelai goreng?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Kacang Kedelai,
 Goreng
      Kalori: 521.0kkal |  Protein: 32.2g | Lemak: 37.7g | Karbohidrat: 22.9g | Serat: 7.6g | Kalsium: 296.0mg | Besi: 6.5mg | Retinol: 20.0mcg | Vit C: 0.0mg
   2. Kacang Kedelai, Rebus
      Kalori: 189.0kkal |  Protein: 20.2g | Lemak: 8.2g | Karbohidrat: 12.7g | Serat: 1.6g | Kalsium: 91.0mg | Besi: 3.9mg | Retinol: 15.0mcg | Vit C: 0.0mg
   3. Kacang Kedelai, Kering
      Kalori: 381.0kkal |  Protein: 40.4g | Lemak: 16.7g | Karbohidrat: 24.9g | Serat: 3.2g | Kalsium: 222.0mg | Besi: 10.0mg | Retinol: 31.0mcg | Vit C: 0.0mg
   4. Kacang Kedelai, Segar
      Kalori: 286.0kkal |  Protein: 30.2g | Lemak: 15.6g | Karbohidrat: 30.1g | Serat: 2.9g | Kalsium: 196.0mg | Besi: 6.9mg | Retinol: 95.0mcg | Vit C: 0.0mg
   5. Tempe Kedelai Murni,
 Goreng
      Kalori: 350.0kkal |  Protein: 24.5g | Lemak: 26.6g | Karbohidrat: 10.4g | Serat: 4.2g | Kalsium: 202.0mg | Besi: 4.9mg | Retinol: 78.0mcg | Vit C: 0.0mg


16. QUERY: "Berapa kalsium dan vitamin A di susu bubuk?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Susu Bubuk
      Kalori: 513.0kkal |  Protein: 24.6g | Lemak: 30.0g | Karbohidrat: 36.2g | Serat: 0.0g | Kalsium: 904.0mg | Besi: 0.6mg | Retinol: 0.0mcg | Vit C: 6.0mg
   2. Susu Asam Untuk Bayi,
 Bubuk
      Kalori: 418.0kkal |  Protein: 19.0g | Lemak: 9.0g | Karbohidrat: 65.5g | Serat: 0.0g | Kalsium: 800.0mg | Besi: 7.0mg | Retinol: 0.0mcg | Vit C: 30.0mg
   3. Susu Skim, Bubuk
      Kalori: 359.0kkal |  Protein: 35.6g | Lemak: 1.0g | Karbohidrat: 52.0g | Serat: 0.0g | Kalsium: 1300.0mg | Besi: 0.6mg | Retinol: 0.0mcg | Vit C: 7.0mg
   4. Susu Kerbau, Segar
      Kalori: 160.0kkal |  Protein: 6.3g | Lemak: 12.0g | Karbohidrat: 7.1g | Serat: 0.0g | Kalsium: 216.0mg | Besi: 0.2mg | Retinol: 0.0mcg | Vit C: 1.0mg
   5. Susu Kental Tak Manis
      Kalori: 138.0kkal |  Protein: 7.0g | Lemak: 7.9g | Karbohidrat: 9.9g | Serat: 0.0g | Kalsium: 243.0mg | Besi: 0.2mg | Retinol: 0.0mcg | Vit C: 1.0mg


17. QUERY: "Kandungan gizi lengkap kecap per 100 gram?"
     → Detected Intent: FOOD_NAME
----------------------------------------------------------------------------------------------------
   1. Kecap
      Kalori: 71.0kkal |  Protein: 5.7g | Lemak: 1.3g | Karbohidrat: 9.0g | Serat: 0.0g | Kalsium: 123.0mg | Besi: 5.7mg | Retinol: 0.0mcg | Vit C: 0.0mg
   2. Tauco Cap Meong
      Kalori: 159.0kkal |  Protein: 7.4g | Lemak: 4.9g | Karbohidrat: 21.3g | Serat: 1.6g | Kalsium: 183.0mg | Besi: 10.1mg | Retinol: 472.0mcg | Vit C: 0.0mg
   3. Pisang Ketip, Segar
      Kalori: 145.0kkal |  Protein: 1.1g | Lemak: 0.3g | Karbohidrat: 34.5g | Serat: 6.6g | Kalsium: 5.0mg | Besi: 0.1mg | Retinol: 0.0mcg | Vit C: 95.0mg
   4. Tempe Kedelai +
 Jagung
      Kalori: 143.0kkal |  Protein: 12.0g | Lemak: 5.5g | Karbohidrat: 11.4g | Serat: 1.9g | Kalsium: 155.0mg | Besi: 6.8mg | Retinol: 1320.0mcg | Vit C: 0.0mg
   5. Gatep, Segar
      Kalori: 191.0kkal |  Protein: 4.5g | Lemak: 1.5g | Karbohidrat: 39.7g | Serat: 13.4g | Kalsium: 186.0mg | Besi: 3.2mg | Retinol: 0.0mcg | Vit C: 0.0mg


18. QUERY: "Apa lemak dan natrium di terasi?"
     → Detected Intent: NUTRITION
----------------------------------------------------------------------------------------------------
   1. Terasi

In [ ]:
import re

# Enum sederhana untuk intent
INTENT_NUTRITION = 'nutrition'  # fokus gizi (tinggi protein, rendah kalori)
INTENT_FOOD_NAME = 'food_name'  # nama spesifik (dada ayam goreng)
INTENT_MEAL_CONTEXT = 'meal_context'  # konteks (sarapan anak, diet diabetes)

def detect_intent(query):
    query_lower = query.lower()

    # Rule 1: Nutrition intent (ada kata gizi seperti protein, besi, kalori)
    nutrition_keywords = ['protein', 'zat besi', 'besi', 'kalori', 'serat', 'kalsium', 'vit', 'vitamin', 'energi', 'lemak', 'natrium', 'karbohidrat', 'kaya', 'tinggi', 'rendah']
    if any(k in query_lower for k in nutrition_keywords):
        return INTENT_NUTRITION

    # Rule 2: Meal/context intent (ada kata konteks seperti sarapan, anak, diet, ibu hamil)
    context_keywords = ['sarapan', 'makan malam', 'cemilan', 'ngemil', 'diet', 'diabetes', 'hamil', 'anak', 'sekolah', 'olahraga', 'atlet', 'penambah darah', 'mengenyangkan']
    if any(k in query_lower for k in context_keywords):
        return INTENT_MEAL_CONTEXT

    # Rule 3: Food name intent (default jika nama makanan spesifik, tanpa keyword gizi/konteks)
    return INTENT_FOOD_NAME

def hybrid_retrieval(query, k=5, candidate_k=50):
    intent = detect_intent(query)
    print(f"Detected intent: {intent}")  # Debug untuk skripsi

    q_embed = model.encode(['query: ' + query], normalize_embeddings=True)

    # Retrieval dasar (semantic top-50)
    results = collection.query(
        query_embeddings=q_embed.tolist(),
        n_results=candidate_k,
        include=["documents", "metadatas", "distances"]
    )

    candidates = results['metadatas'][0] if results['metadatas'] else []

    # Routing berdasarkan intent
    if intent == INTENT_NUTRITION:
        # Standard: Parse criteria + rerank numeric
        criteria = parse_query(query)
        if criteria:
            sorted_cands = sorted(
                candidates,
                key=lambda x: float(x.get(criteria['col'], 0) or 0),
                reverse=(criteria['order'] == 'desc')
            )
            return sorted_cands[:k]

    elif intent == INTENT_FOOD_NAME:
        # Boost keyword match: Sort by distance (semantic) + keyword di nama
        protein_keywords = re.findall(r'\b(ayam|tempe|ikan|daging|sapi|kambing)\b', query.lower())  # Extract protein utama
        if protein_keywords:
            sorted_cands = sorted(
                candidates,
                key=lambda x: (-sum(k in x['nama'].lower() for k in protein_keywords),  # Boost utama
                               results['distances'][0][candidates.index(x)])  # Tie-breaker distance
            )
        else:
            sorted_cands = sorted(candidates, key=lambda x: results['distances'][0][candidates.index(x)])
        return sorted_cands[:k]

    elif intent == INTENT_MEAL_CONTEXT:
        # Heuristic filter: Exclude "mentah", "kering", "bubuk" jika konteks anak/sarapan
        filtered_cands = [c for c in candidates if all(w not in c['nama'].lower() for w in ['mentah', 'kering', 'bubuk', 'dendeng'])]
        if not filtered_cands:
            filtered_cands = candidates  # Fallback jika terlalu ketat

        # Lalu rerank numeric jika ada criteria
        criteria = parse_query(query)
        if criteria:
            sorted_cands = sorted(
                filtered_cands,
                key=lambda x: float(x.get(criteria['col'], 0) or 0),
                reverse=(criteria['order'] == 'desc')
            )
        else:
            sorted_cands = sorted(filtered_cands, key=lambda x: results['distances'][0][candidates.index(x)])
        return sorted_cands[:k]

    # Fallback jika None
    return candidates[:k]

In [ ]:
test_cases = [
    {
        "query": "Berapa kandungan gizi lengkap beras giling mentah per 100 gram?",
        "expected": "beras giling"
    },
    {
        "query": "Apa saja zat gizi dalam beras hitam mentah, termasuk energi dan protein?",
        "expected": "beras hitam"
    },
    {
        "query": "Kandungan kalori, protein, dan lemak di beras jagung kuning kering mentah per 100 gram?",
        "expected": "beras jagung kuning"
    },
    {
        "query": "Berapa besi dan kalsium dalam beras ketan hitam tumbuk mentah?",
        "expected": "beras ketan hitam"
    },
    {
        "query": "Kandungan gizi lengkap tempe kedelai murni goreng per 100 gram?",
        "expected": "tempe kedelai murni"
    },
    {
        "query": "Apa protein dan serat di tempe pasar goreng?",
        "expected": "tempe pasar"
    },
    {
        "query": "Kandungan energi, lemak, dan karbohidrat di tempe lamtoro?",
        "expected": "tempe lamtoro"
    },
    {
        "query": "Berapa vitamin A dan besi dalam ayam goreng Kentucky dada?",
        "expected": "ayam goreng kentucky, dada"
    },
    {
        "query": "Kandungan gizi lengkap ayam goreng Church Texas dada per 100 gram?",
        "expected": "ayam goreng church texas, dada"
    },
    {
        "query": "Apa kalori dan protein di ayam hati segar?",
        "expected": "ayam hati"
    },
    {
        "query": "Kandungan besi, kalsium, dan vitamin C di ikan mujahir segar?",
        "expected": "ikan mujahir"
    },
    {
        "query": "Berapa protein dan lemak di ikan teri kering tawar mentah?",
        "expected": "ikan teri"
    },
    {
        "query": "Kandungan gizi lengkap ikan sale lais mentah per 100 gram?",
        "expected": "ikan sale lais"
    },
    {
        "query": "Apa energi dan serat di jagung muda kuning mentah?",
        "expected": "jagung muda kuning"
    },
    {
        "query": "Kandungan kalori, protein, dan besi di kacang kedelai goreng?",
        "expected": "kacang kedelai"
    },
    {
        "query": "Berapa kalsium dan vitamin A di susu bubuk?",
        "expected": "susu bubuk"
    },
    {
        "query": "Kandungan gizi lengkap kecap per 100 gram?",
        "expected": "kecap"
    },
    {
        "query": "Apa lemak dan natrium di terasi?",
        "expected": "terasi"
    },
    {
        "query": "Kandungan besi dan protein di oncom kacang tanah pepes?",
        "expected": "oncom kacang tanah"
    },
    {
        "query": "Berapa kalori dan serat di rebung segar?",
        "expected": "rebung"
    },
    {
        "query": "Kandungan gizi lengkap daun singkong segar per 100 gram?",
        "expected": "daun singkong"
    },
    {
        "query": "Apa protein dan vitamin C di jambu biji segar?",
        "expected": "jambu biji"
    },
    {
        "query": "Kandungan energi, lemak, dan kalsium di keju?",
        "expected": "keju"
    },
    {
        "query": "Berapa besi dan vitamin A di hati babi segar?",
        "expected": "hati babi"
    },
    {
        "query": "Kandungan gizi lengkap nasi per 100 gram?",
        "expected": "nasi"
    },
    {
        "query": "Apa serat dan karbohidrat di beras merah nasi?",
        "expected": "beras merah"
    },
    {
        "query": "Kandungan protein, besi, dan kalium di kacang bogor kering?",
        "expected": "kacang bogor"
    },
    {
        "query": "Berapa kalori dan lemak di martabak india?",
        "expected": "martabak india"
    },
    {
        "query": "Kandungan gizi lengkap mie ayam per 100 gram?",
        "expected": "mie ayam"
    },
    {
        "query": "Apa vitamin C dan besi di cabai merah segar?",
        "expected": "cabai merah"
    },
    {
        "query": "Kandungan energi, protein, dan serat di durian segar?",
        "expected": "durian"
    },
    {
        "query": "Berapa kalsium dan besi di ikan bandeng presto masakan?",
        "expected": "ikan bandeng presto"
    },
    {
        "query": "Kandungan gizi lengkap sop buntut masakan per 100 gram?",
        "expected": "sop buntut"
    },
    {
        "query": "Apa lemak dan natrium di saos tomat?",
        "expected": "saos tomat"
    },
    {
        "query": "Kandungan protein dan vitamin A di daun mangkokan segar?",
        "expected": "daun mangkokan"
    },
    {
        "query": "Berapa besi dan serat di kacang endel biji kering?",
        "expected": "kacang endel"
    },
    {
        "query": "Kandungan gizi lengkap petis udang pasta per 100 gram?",
        "expected": "petis udang"
    },
    {
        "query": "Apa kalori dan kalsium di air kelapa muda segar?",
        "expected": "air kelapa muda"
    },
    {
        "query": "Kandungan energi, lemak, dan karbohidrat di biskuit?",
        "expected": "biskuit"
    },
    {
        "query": "Berapa protein dan besi di daging sapi kornet?",
        "expected": "daging sapi kornet"
    },
    {
        "query": "Kandungan gizi lengkap gado-gado per 100 gram?",
        "expected": "gado-gado"
    },
    {
        "query": "Apa serat dan vitamin C di salak medan segar?",
        "expected": "salak medan"
    },
    {
        "query": "Kandungan besi, kalsium, dan vitamin A di genjer segar?",
        "expected": "genjer"
    },
    {
        "query": "Berapa kalori dan protein di bakwan?",
        "expected": "bakwan"
    },
    {
        "query": "Kandungan gizi lengkap rendang sapi masakan per 100 gram?",
        "expected": "rendang sapi"
    },
    {
        "query": "Apa lemak dan natrium di bekasam?",
        "expected": "bekasam"
    },
    {
        "query": "Kandungan energi, serat, dan besi di cabai merah kering?",
        "expected": "cabai merah"
    },
    {
        "query": "Berapa vitamin A dan kalsium di andaliman segar?",
        "expected": "andaliman"
    },
    {
        "query": "Kandungan gizi lengkap kwaci per 100 gram?",
        "expected": "kwaci"
    },
    {
        "query": "Apa protein, besi, dan kalium di wijen mentah?",
        "expected": "wijen"
    },
     {
        "query": "Berapa protein pada paha ayam?",
        "expected": "paha ayam"
    }
]

In [ ]:
import pandas as pd

def soft_match(a, b):
    a_tokens = set(a.split())
    b_tokens = set(b.split())
    return len(a_tokens & b_tokens) / len(a_tokens) >= 0.7


def normalize(text):
    return text.lower().replace(",", "").replace("\n", " ").strip()

def evaluate_retrieval(test_cases, k=3):
    rows = []
    correct = 0

    for i, case in enumerate(test_cases, start=1):
        query = case["query"]

        # ✅ normalize ground truth
        expected = normalize(case["expected"])

        results = hybrid_retrieval(query, k=k)

        # ambil nama hasil retrieval
        retrieved_names = [r["nama"] for r in results]

        # ✅ normalize hasil retrieval
        retrieved_normalized = [normalize(n) for n in retrieved_names]


        # matching (token-based, robust)
        found = any(
            soft_match(expected, name)
            for name in retrieved_normalized
        )

        status = "✅" if found else "❌"

        if found:
            correct += 1

        rows.append({
            "No": i,
            "Query": query,
            "Ground Truth": expected,
            "Top-1": retrieved_names[0] if retrieved_names else "-",
            "Top-K Found": "Ya" if found else "Tidak",
            "Status": status
        })

    accuracy = correct / len(test_cases)
    df = pd.DataFrame(rows)

    return df, accuracy

In [ ]:
df1, acc1 = evaluate_retrieval(test_cases, k=1)
df3, acc3 = evaluate_retrieval(test_cases, k=3)
df5, acc5 = evaluate_retrieval(test_cases, k=5)

print(f"Top-1 Accuracy: {acc1:.2%}")
print(f"Top-3 Accuracy: {acc3:.2%}")
print(f"Top-5 Accuracy: {acc5:.2%}")

display(df3)

Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Detected intent: nutrition
Detected intent: food_name
Detected intent: nutrition
Detected intent: nutrition
Top-1 Accuracy: 100.00%
Top-3 Accuracy: 100.00%
Top-5 Accuracy: 100.00%

,No,Query,Ground Truth,Top-1,Top-K Found,Status
0,1,Berapa kandungan gizi lengkap beras giling men...,beras giling,"Beras Giling, Mentah",Ya,✅
1,2,"Apa saja zat gizi dalam beras hitam mentah, te...",beras hitam,"Beras Hitam, Mentah",Ya,✅
2,3,"Kandungan kalori, protein, dan lemak di beras ...",beras jagung kuning,"Beras Jagung Kuning, Kering, Mentah",Ya,✅
3,4,Berapa besi dan kalsium dalam beras ketan hita...,beras ketan hitam,"Beras Ketan Hitam \nTumbuk, Mentah",Ya,✅
4,5,Kandungan gizi lengkap tempe kedelai murni gor...,tempe kedelai murni,"Tempe Kedelai Murni,\n Mentah",Ya,✅
5,6,Apa protein dan serat di tempe pasar goreng?,tempe pasar,Tempe Pasar Goreng,Ya,✅
6,7,"Kandungan energi, lemak, dan karbohidrat di te...",tempe lamtoro,"Tempe Lamtoro Var,\n Gung Dengan Kulit",Ya,✅
7,8,Berapa vitamin A dan besi dalam ayam goreng Ke...,ayam goreng kentucky dada,"Ayam Goreng\n Kentucky, Dada",Ya,✅
8,9,Kandungan gizi lengkap ayam goreng Church Texa...,ayam goreng church texas dada,"Ayam Goreng Church\n Texas, Dada",Ya,✅
9,10,Apa kalori dan protein di ayam hati segar?,ayam hati,"Ayam, Hati, Segar",Ya,✅
10,11,"Kandungan besi, kalsium, dan vitamin C di ikan...",ikan mujahir,"Ikan Mujahir, Segar",Ya,✅
11,12,Berapa protein dan lemak di ikan teri kering t...,ikan teri,"Ikan Teri, Kering,\n Tawar, Mentah",Ya,✅
12,13,Kandungan gizi lengkap ikan sale lais mentah p...,ikan sale lais,"Ikan Sale Lais, Mentah",Ya,✅
13,14,Apa energi dan serat di jagung muda kuning men...,jagung muda kuning,"Jagung Muda, Kuning, Mentah",Ya,✅
14,15,"Kandungan kalori, protein, dan besi di kacang ...",kacang kedelai,"Kacang Kedelai,\n Goreng",Ya,✅
15,16,Berapa kalsium dan vitamin A di susu bubuk?,susu bubuk,Susu Bubuk,Ya,✅
16,17,Kandungan gizi lengkap kecap per 100 gram?,kecap,Kecap,Ya,✅
17,18,Apa lemak dan natrium di terasi?,terasi,Terasi,Ya,✅
18,19,Kandungan besi dan protein di oncom kacang tan...,oncom kacang tanah,Oncom Kacang Tanah\n Pepes,Ya,✅
19,20,Berapa kalori dan serat di rebung segar?,rebung,"Rebung, Segar",Ya,✅
20,21,Kandungan gizi lengkap daun singkong segar per...,daun singkong,"Daun Singkong, Segar",Ya,✅
21,22,Apa protein dan vitamin C di jambu biji segar?,jambu biji,Jambu Biji,Ya,✅
22,23,"Kandungan energi, lemak, dan kalsium di keju?",keju,Keju,Ya,✅
23,24,Berapa besi dan vitamin A di hati babi segar?,hati babi,"Babi, Hati, Segar",Ya,✅
24,25,Kandungan gizi lengkap nasi per 100 gram?,nasi,Nasi,Ya,✅
25,26,Apa serat dan karbohidrat di beras merah nasi?,beras merah,"Beras Merah, Nasi",Ya,✅
26,27,"Kandungan protein, besi, dan kalium di kacang ...",kacang bogor,"Kacang Bogor, Kering",Ya,✅
27,28,Berapa kalori dan lemak di martabak india?,martabak india,Martabak India,Ya,✅
28,29,Kandungan gizi lengkap mie ayam per 100 gram?,mie ayam,Mie Ayam,Ya,✅
29,30,Apa vitamin C dan besi di cabai merah segar?,cabai merah,"Cabai Merah, Segar",Ya,✅
30,31,"Kandungan energi, protein, dan serat di durian...",durian,"Durian, Segar",Ya,✅
31,32,Berapa kalsium dan besi di ikan bandeng presto...,ikan bandeng presto,"Ikan Bandeng Presto,\n Masakan",Ya,✅
32,33,Kandungan gizi lengkap sop buntut masakan per ...,sop buntut,"Sop Buntut, Masakan",Ya,✅
33,34,Apa lemak dan natrium di saos tomat?,saos tomat,Saos Tomat,Ya,✅
34,35,Kandungan protein dan vitamin A di daun mangko...,daun mangkokan,"Daun Mangkokan,\n Segar",Ya,✅
35,36,Berapa besi dan serat di kacang endel biji ker...,kacang endel,"Kacang Endel, Biji,\n Kering",Ya,✅
36,37,Kandungan gizi lengkap petis udang pasta per 1...,petis udang,Petis Udang Pasta,Ya,✅
37,38,Apa kalori dan kalsium di air kelapa muda segar?,air kelapa muda,"Kelapa Muda, Air,\n Segar",Ya,✅
38,39,"Kandungan energi, lemak, dan karbohidrat di bi...",biskuit,Biskuit,Ya,✅
39,40,Berapa protein dan besi di daging sapi kornet?,daging sapi kornet,"Sapi, Daging, Kornet",Ya,✅
40,41,Kandungan gizi lengkap gado-gado per 100 gram?,gado-gado,Gado-Gado,Ya,✅
41,42,Apa serat dan vitamin C di salak medan segar?,salak medan,"Salak Medan, Segar",Ya,✅
42,43,"Kandungan besi, kalsium, dan vitamin A di genj...",genjer,"Genjer, Segar",Ya,✅
43,44,Berapa kalori dan protein di bakwan?,bakwan,Bakwan,Ya,✅
44,45,Kandungan gizi lengkap rendang sapi masakan pe...,rendang sapi,"Rendang Sapi,\n Masakan",Ya,✅
45,46,Apa lemak dan natrium di bekasam?,bekasam,Bekasam,Ya,✅
46,47,"Kandungan energi, serat, dan besi di cabai mer...",cabai merah,"Cabai Merah, Kering",Ya,✅
47,48,Berapa vitamin A dan kalsium di andaliman segar?,andaliman,"Andaliman, Segar",Ya,✅
48,49,Kandungan gizi lengkap kwaci per 100 gram?,kwaci,Kwaci,Ya,✅
49,50,"Apa protein, besi, dan kalium di wijen mentah?",wijen,"Wijen, Mentah",Ya,✅
50,51,Berapa protein pada paha ayam?,paha ayam,"Ayam Goreng\n Church,Texas Paha",Ya,✅

In [ ]:
!pip install --upgrade opentelemetry-api opentelemetry-sdk

Requirement already satisfied: opentelemetry-api in /usr/local/lib/python3.12/dist-packages (1.41.0)
Requirement already satisfied: opentelemetry-sdk in /usr/local/lib/python3.12/dist-packages (1.41.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (8.7.1)
Requirement already satisfied: typing-extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-api) (4.15.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk) (0.62b0)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api) (3.23.0)

In [ ]:
import sys
from sentence_transformers import SentenceTransformer

# --- KONFIGURASI PATH ---
CHROMA_PATH = "/content/drive/MyDrive/skripsian/chroma_db/chroma_tkpi_full"
BASE_PATH = "/content/drive/MyDrive/skripsian/Notebook"

# Tambahkan path agar bisa membaca file ingredient_recommender.py
if BASE_PATH not in sys.path:
    sys.path.append(BASE_PATH)

try:
    from ingredient_recommender import IngredientRecommender
except ImportError as e:
    print(f"Gagal import modul: {e}")

# --- 1. LOAD MODEL EMBEDDING & CHROMADB ---
print("Memuat Model Embedding (intfloat/multilingual-e5-large...")
embed_model = SentenceTransformer('intfloat/multilingual-e5-large')

print("Terhubung ke ChromaDB...\n")
recommender = IngredientRecommender(CHROMA_PATH, embed_model)

Memuat Model Embedding (intfloat/multilingual-e5-large...

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Terhubung ke ChromaDB...

In [ ]:
# --- 2. SKENARIO PENGUJIAN ---
tujuan_list = ['cutting', 'bulking', 'maintain']

# --- 2. JALANKAN PERULANGAN ---
for tujuan in tujuan_list:
    print(f"======================================================")
    print(f" 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : {tujuan.upper()}")
    print(f"======================================================")

    # Pastikan variabel 'recommender' sudah ada (hasil load model sebelumnya)
    basket = recommender.get_balanced_basket(tujuan)

    # Menampilkan hasil Karbohidrat
    print("\n[🍚 KATEGORI: KARBOHIDRAT]")
    if basket['karbo']:
        for i, item in enumerate(basket['karbo'], 1):
            print(f"  {i}. {item['nama']} | Energi: {item.get('kalori', 0)} kkal | Karbo: {item.get('karbo', 0)}g | Serat: {item.get('serat', 0)}g")
    else:
        print("   (Data Kosong)")

    # Menampilkan hasil Protein (Lauk)
    print("\n[🍗 KATEGORI: PROTEIN / LAUK]")
    if basket['protein']:
        for i, item in enumerate(basket['protein'], 1):
            print(f"  {i}. {item['nama']} | Energi: {item.get('kalori', 0)} kkal | Protein: {item.get('protein', 0)}g | Lemak: {item.get('lemak', 0)}g")
    else:
        print("   (Data Kosong)")

    # Menampilkan hasil Serat (Sayur)
    print("\n[🥦 KATEGORI: SAYUR & SERAT]")
    if basket['serat']:
        for i, item in enumerate(basket['serat'], 1):
            print(f"  {i}. {item['nama']} | Energi: {item.get('kalori', 0)} kkal | Serat: {item.get('serat', 0)}g")
    else:
        print("   (Data Kosong)")

    print("\n" + "="*54 + "\n")
for tujuan in tujuan_list:
    print(f"======================================================")
    print(f" 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : {tujuan.upper()}")
    print(f"======================================================")

    basket = recommender.get_balanced_basket(tujuan)

    # Menampilkan hasil Karbohidrat
    print("\n[🍚 KATEGORI: KARBOHIDRAT]")
    for i, item in enumerate(basket['karbo'], 1):
        # Langsung ambil dari dictionary 'item' yang sudah diproses oleh modul .py
        print(f"  {i}. {item['nama']} | Energi: {item['kalori']} kkal | Karbo: {item['karbo']}g | Serat: {item['serat']}g")

    # Menampilkan hasil Protein (Lauk)
    print("\n[🍗 KATEGORI: PROTEIN / LAUK]")
    for i, item in enumerate(basket['protein'], 1):
        print(f"  {i}. {item['nama']} | Energi: {item['kalori']} kkal | Protein: {item['protein']}g | Lemak: {item['lemak']}g")

    # Menampilkan hasil Serat (Sayur)
    print("\n[🥦 KATEGORI: SAYUR & SERAT]")
    for i, item in enumerate(basket['serat'], 1):
        print(f"  {i}. {item['nama']} | Energi: {item['kalori']} kkal | Serat: {item['serat']}g")

    print("\n" + "="*54 + "\n")

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : CUTTING
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Beras Merah, Nasi | Energi: 149.0 kkal | Karbo: 32.5g | Serat: 0.3g
  2. Ubi Jalar Merah, Segar | Energi: 151.0 kkal | Karbo: 35.4g | Serat: 0.7g
  3. Batatas Tali, Ubi, Rebus | Energi: 182.0 kkal | Karbo: 42.2g | Serat: 9.2g
  4. Ubi Jalar, Kuning,
 Kukus | Energi: 100.0 kkal | Karbo: 23.8g | Serat: 1.0g
  5. Kaburan, Ubi, Segar | Energi: 133.0 kkal | Karbo: 32.2g | Serat: 0.7g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Ikan Peda Banjar,
 Mentah | Energi: 156.0 kkal | Protein: 28.0g | Lemak: 4.0g
  2. Ikan Mujahir Pepes | Energi: 121.0 kkal | Protein: 21.7g | Lemak: 2.8g
  3. Ikan Calo/ Peda,
 Mentah | Energi: 81.0 kkal | Protein: 11.4g | Lemak: 1.9g
  4. Ikan Sanggang,
 Masakan | Energi: 240.0 kkal | Protein: 21.7g | Lemak: 7.7g
  5. Ikan Pepetek, Mentah | Energi: 176.0 kkal | Protein: 32.0g | Lemak: 4.4g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Pelecing Kangkung | Energi: 75.0 kkal | Serat: 5.4g
  2. Kangkung, Kukus | Energi: 30.0 kkal | Serat: 1.8g
  3. Kangkung, Segar | Energi: 28.0 kkal | Serat: 2.0g
  4. Kangkung, Rebus | Energi: 22.0 kkal | Serat: 1.2g
  5. Kangkung Tondano | Energi: 43.0 kkal | Serat: 4.3g

======================================================

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : BULKING
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Roti Putih | Energi: 248.0 kkal | Karbo: 50.0g | Serat: 9.1g
  2. Beras Merah, Nasi | Energi: 149.0 kkal | Karbo: 32.5g | Serat: 0.3g
  3. Roti Boong | Energi: 341.0 kkal | Karbo: 43.3g | Serat: 0.0g
  4. Beras Giling Var Pelita, Mentah | Energi: 369.0 kkal | Karbo: 77.1g | Serat: 0.4g
  5. Beras Giling Var
Rojolele, Mentah | Energi: 357.0 kkal | Karbo: 77.1g | Serat: 0.2g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Telur Ayam Ras, Bagian
 Kuning, Segar | Energi: 355.0 kkal | Protein: 16.3g | Lemak: 31.9g
  2. Telur Ayam, Dadar,
 Masakan | Energi: 251.0 kkal | Protein: 16.3g | Lemak: 19.4g
  3. Ayam Goreng
 Kentucky, Dada | Energi: 298.0 kkal | Protein: 34.2g | Lemak: 16.8g
  4. Ayam Goreng
 Kentucky, Paha | Energi: 286.0 kkal | Protein: 32.1g | Lemak: 16.1g
  5. Telur Ayam Kampung,
 Segar | Energi: 174.0 kkal | Protein: 10.8g | Lemak: 14.0g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Sie Reuboh, Masakan | Energi: 474.0 kkal | Serat: 0.0g
  2. Tumis Keumamah | Energi: 300.0 kkal | Serat: 4.5g
  3. Lawara Jangang,
 Masakan | Energi: 159.0 kkal | Serat: 0.0g
  4. Sayur Lilin-Terubuk | Energi: 36.0 kkal | Serat: 1.4g
  5. Talas Bogor, Kukus | Energi: 120.0 kkal | Serat: 0.7g

======================================================

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : MAINTAIN
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Jagung Nasi, Mentah | Energi: 357.0 kkal | Karbo: 79.5g | Serat: 6.2g
  2. Beras Jagung Kuning, Kering, Mentah | Energi: 358.0 kkal | Karbo: 82.7g | Serat: 10.0g
  3. Beras Jagung Putih,
Kering, Mentah | Energi: 307.0 kkal | Karbo: 71.8g | Serat: 10.0g
  4. Jagung, Tepung Putih | Energi: 355.0 kkal | Karbo: 73.7g | Serat: 7.2g
  5. Jagung Muda, Kuning, Mentah | Energi: 147.0 kkal | Karbo: 31.5g | Serat: 1.3g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Ikan Lais Bakar | Energi: 147.0 kkal | Protein: 17.5g | Lemak: 6.5g
  2. Ikan Baung Bakar | Energi: 144.0 kkal | Protein: 17.8g | Lemak: 5.8g
  3. Telur Aayam Ras,
 Bagian Putih, Segar | Energi: 50.0 kkal | Protein: 10.8g | Lemak: 0.0g
  4. Telur Ayam, Dadar,
 Masakan | Energi: 251.0 kkal | Protein: 16.3g | Lemak: 19.4g
  5. Telur Ayam Ras, Segar | Energi: 154.0 kkal | Protein: 12.4g | Lemak: 10.8g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Kangkung, Kukus | Energi: 30.0 kkal | Serat: 1.8g
  2. Kangkung, Segar | Energi: 28.0 kkal | Serat: 2.0g
  3. Kangkung, Rebus | Energi: 22.0 kkal | Serat: 1.2g
  4. Kangkung Tondano | Energi: 43.0 kkal | Serat: 4.3g
  5. Pelecing Kangkung | Energi: 75.0 kkal | Serat: 5.4g

======================================================

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : CUTTING
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Beras Merah, Nasi | Energi: 149.0 kkal | Karbo: 32.5g | Serat: 0.3g
  2. Ubi Jalar Merah, Segar | Energi: 151.0 kkal | Karbo: 35.4g | Serat: 0.7g
  3. Batatas Tali, Ubi, Rebus | Energi: 182.0 kkal | Karbo: 42.2g | Serat: 9.2g
  4. Ubi Jalar, Kuning,
 Kukus | Energi: 100.0 kkal | Karbo: 23.8g | Serat: 1.0g
  5. Kaburan, Ubi, Segar | Energi: 133.0 kkal | Karbo: 32.2g | Serat: 0.7g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Ikan Peda Banjar,
 Mentah | Energi: 156.0 kkal | Protein: 28.0g | Lemak: 4.0g
  2. Ikan Mujahir Pepes | Energi: 121.0 kkal | Protein: 21.7g | Lemak: 2.8g
  3. Ikan Calo/ Peda,
 Mentah | Energi: 81.0 kkal | Protein: 11.4g | Lemak: 1.9g
  4. Ikan Sanggang,
 Masakan | Energi: 240.0 kkal | Protein: 21.7g | Lemak: 7.7g
  5. Ikan Pepetek, Mentah | Energi: 176.0 kkal | Protein: 32.0g | Lemak: 4.4g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Pelecing Kangkung | Energi: 75.0 kkal | Serat: 5.4g
  2. Kangkung, Kukus | Energi: 30.0 kkal | Serat: 1.8g
  3. Kangkung, Segar | Energi: 28.0 kkal | Serat: 2.0g
  4. Kangkung, Rebus | Energi: 22.0 kkal | Serat: 1.2g
  5. Kangkung Tondano | Energi: 43.0 kkal | Serat: 4.3g

======================================================

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : BULKING
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Roti Putih | Energi: 248.0 kkal | Karbo: 50.0g | Serat: 9.1g
  2. Beras Merah, Nasi | Energi: 149.0 kkal | Karbo: 32.5g | Serat: 0.3g
  3. Roti Boong | Energi: 341.0 kkal | Karbo: 43.3g | Serat: 0.0g
  4. Beras Giling Var Pelita, Mentah | Energi: 369.0 kkal | Karbo: 77.1g | Serat: 0.4g
  5. Beras Giling Var
Rojolele, Mentah | Energi: 357.0 kkal | Karbo: 77.1g | Serat: 0.2g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Telur Ayam Ras, Bagian
 Kuning, Segar | Energi: 355.0 kkal | Protein: 16.3g | Lemak: 31.9g
  2. Telur Ayam, Dadar,
 Masakan | Energi: 251.0 kkal | Protein: 16.3g | Lemak: 19.4g
  3. Ayam Goreng
 Kentucky, Dada | Energi: 298.0 kkal | Protein: 34.2g | Lemak: 16.8g
  4. Ayam Goreng
 Kentucky, Paha | Energi: 286.0 kkal | Protein: 32.1g | Lemak: 16.1g
  5. Telur Ayam Kampung,
 Segar | Energi: 174.0 kkal | Protein: 10.8g | Lemak: 14.0g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Sie Reuboh, Masakan | Energi: 474.0 kkal | Serat: 0.0g
  2. Tumis Keumamah | Energi: 300.0 kkal | Serat: 4.5g
  3. Lawara Jangang,
 Masakan | Energi: 159.0 kkal | Serat: 0.0g
  4. Sayur Lilin-Terubuk | Energi: 36.0 kkal | Serat: 1.4g
  5. Talas Bogor, Kukus | Energi: 120.0 kkal | Serat: 0.7g

======================================================

======================================================
 🔍 HASIL PENCARIAN RAG UNTUK TUJUAN : MAINTAIN
======================================================

[🍚 KATEGORI: KARBOHIDRAT]
  1. Jagung Nasi, Mentah | Energi: 357.0 kkal | Karbo: 79.5g | Serat: 6.2g
  2. Beras Jagung Kuning, Kering, Mentah | Energi: 358.0 kkal | Karbo: 82.7g | Serat: 10.0g
  3. Beras Jagung Putih,
Kering, Mentah | Energi: 307.0 kkal | Karbo: 71.8g | Serat: 10.0g
  4. Jagung, Tepung Putih | Energi: 355.0 kkal | Karbo: 73.7g | Serat: 7.2g
  5. Jagung Muda, Kuning, Mentah | Energi: 147.0 kkal | Karbo: 31.5g | Serat: 1.3g

[🍗 KATEGORI: PROTEIN / LAUK]
  1. Ikan Lais Bakar | Energi: 147.0 kkal | Protein: 17.5g | Lemak: 6.5g
  2. Ikan Baung Bakar | Energi: 144.0 kkal | Protein: 17.8g | Lemak: 5.8g
  3. Telur Aayam Ras,
 Bagian Putih, Segar | Energi: 50.0 kkal | Protein: 10.8g | Lemak: 0.0g
  4. Telur Ayam, Dadar,
 Masakan | Energi: 251.0 kkal | Protein: 16.3g | Lemak: 19.4g
  5. Telur Ayam Ras, Segar | Energi: 154.0 kkal | Protein: 12.4g | Lemak: 10.8g

[🥦 KATEGORI: SAYUR & SERAT]
  1. Kangkung, Kukus | Energi: 30.0 kkal | Serat: 1.8g
  2. Kangkung, Segar | Energi: 28.0 kkal | Serat: 2.0g
  3. Kangkung, Rebus | Energi: 22.0 kkal | Serat: 1.2g
  4. Kangkung Tondano | Energi: 43.0 kkal | Serat: 4.3g
  5. Pelecing Kangkung | Energi: 75.0 kkal | Serat: 5.4g

======================================================

In [ ]:
import sys
from sentence_transformers import SentenceTransformer

# --- KONFIGURASI PATH ---
CHROMA_PATH = "/content/drive/MyDrive/skripsian/chroma_db/chroma_tkpi_full"
BASE_PATH = "/content/drive/MyDrive/skripsian/Notebook"
if BASE_PATH not in sys.path: sys.path.append(BASE_PATH)

from ingredient_recommender import IngredientRecommender

# --- 1. LOAD MODEL EMBEDDING & CHROMADB ---
print("Memuat Model & Terhubung ke ChromaDB...\n")
embed_model = SentenceTransformer('intfloat/multilingual-e5-large')
recommender = IngredientRecommender(CHROMA_PATH, embed_model)

Memuat Model & Terhubung ke ChromaDB...

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

XLMRobertaModel LOAD REPORT from: intfloat/multilingual-e5-large
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
# --- 2. FUNGSI EVALUATOR GIZI (GROUND TRUTH) ---
def evaluate_relevance(item, category, goal):
    """
    Mengevaluasi apakah makanan yang ditarik ChromaDB sesuai dengan tujuan diet.
    Mengembalikan True (Relevan) atau False (Tidak Relevan).
    """
    kalori = float(item.get('kalori', 0))
    protein = float(item.get('protein', 0))
    lemak = float(item.get('lemak', 0))

    if goal == 'cutting':
        # Cutting: Kalori jangan terlalu tinggi, Lemak harus rendah.
        if category == 'karbo': return kalori <= 250
        if category == 'protein': return lemak <= 15.0 # Jika lemak > 15g (misal gorengan), maka SALAH (False)
        if category == 'serat': return True

    elif goal == 'bulking':
        # Bulking: Butuh padat kalori dan protein tinggi.
        if category == 'karbo': return kalori >= 100
        if category == 'protein': return protein >= 15.0
        if category == 'serat': return True

    elif goal == 'maintain':
        # Maintain: Wajar dan seimbang, lemak jangan ekstrem.
        if category == 'protein': return lemak <= 20.0
        return True

    return True

# --- 3. JALANKAN PENGUJIAN OTOMATIS ---
tujuan_list = ['cutting', 'bulking', 'maintain']
total_all_items = 0
total_all_relevant = 0

print("======================================================")
print(" 🤖 MEMULAI EVALUASI AKURASI RAG (PRECISION SCORE)")
print("======================================================")

for tujuan in tujuan_list:
    basket = recommender.get_balanced_basket(tujuan)
    categories = ['karbo', 'protein', 'serat']

    relevant_count = 0
    total_count = 0

    print(f"\n👉 TARGET: {tujuan.upper()}")

    for cat in categories:
        for item in basket[cat]:
            # Evaluasi item berdasarkan aturan gizi di atas
            is_relevant = evaluate_relevance(item, cat, tujuan)

            # Update statistik
            total_count += 1
            if is_relevant: relevant_count += 1

            # Format tampilan
            status = "✅ RELEVAN" if is_relevant else "❌ TIDAK RELEVAN"
            print(f"   [{cat.upper()}] {item['nama']} (Kal:{item.get('kalori',0)}, Pro:{item.get('protein',0)}, Lem:{item.get('lemak',0)}) -> {status}")

    # Hitung Precision per kategori
    precision = (relevant_count / total_count) * 100
    print(f"   📊 Akurasi {tujuan.upper()}: {relevant_count}/{total_count} Item ({precision:.2f}%)")
    print("-" * 54)

    total_all_items += total_count
    total_all_relevant += relevant_count

# --- 4. HASIL AKHIR KESELURUHAN ---
overall_precision = (total_all_relevant / total_all_items) * 100
print(f"\n======================================================")
print(f" 🎯 TOTAL AKURASI SISTEM RAG (MEAN PRECISION) : {overall_precision:.2f}%")
print(f"======================================================")

======================================================
 🤖 MEMULAI EVALUASI AKURASI RAG (PRECISION SCORE)
======================================================

👉 TARGET: CUTTING
   [KARBO] Beras Merah, Nasi (Kal:149.0, Pro:2.8, Lem:0.4) -> ✅ RELEVAN
   [KARBO] Ubi Jalar Merah, Segar (Kal:151.0, Pro:1.6, Lem:0.3) -> ✅ RELEVAN
   [KARBO] Batatas Tali, Ubi, Rebus (Kal:182.0, Pro:2.4, Lem:0.4) -> ✅ RELEVAN
   [KARBO] Ubi Jalar, Kuning,
 Kukus (Kal:100.0, Pro:0.7, Lem:0.3) -> ✅ RELEVAN
   [KARBO] Kaburan, Ubi, Segar (Kal:133.0, Pro:1.0, Lem:0.2) -> ✅ RELEVAN
   [PROTEIN] Ikan Peda Banjar,
 Mentah (Kal:156.0, Pro:28.0, Lem:4.0) -> ✅ RELEVAN
   [PROTEIN] Ikan Mujahir Pepes (Kal:121.0, Pro:21.7, Lem:2.8) -> ✅ RELEVAN
   [PROTEIN] Ikan Calo/ Peda,
 Mentah (Kal:81.0, Pro:11.4, Lem:1.9) -> ✅ RELEVAN
   [PROTEIN] Ikan Sanggang,
 Masakan (Kal:240.0, Pro:21.7, Lem:7.7) -> ✅ RELEVAN
   [PROTEIN] Ikan Pepetek, Mentah (Kal:176.0, Pro:32.0, Lem:4.4) -> ✅ RELEVAN
   [SERAT] Pelecing Kangkung (Kal:75.0, Pro:2.5, Lem:2.8) -> ✅ RELEVAN
   [SERAT] Kangkung, Kukus (Kal:30.0, Pro:3.2, Lem:0.7) -> ✅ RELEVAN
   [SERAT] Kangkung, Segar (Kal:28.0, Pro:3.4, Lem:0.7) -> ✅ RELEVAN
   [SERAT] Kangkung, Rebus (Kal:22.0, Pro:2.5, Lem:0.6) -> ✅ RELEVAN
   [SERAT] Kangkung Tondano (Kal:43.0, Pro:1.8, Lem:0.2) -> ✅ RELEVAN
   📊 Akurasi CUTTING: 15/15 Item (100.00%)
------------------------------------------------------

👉 TARGET: BULKING
   [KARBO] Roti Putih (Kal:248.0, Pro:8.0, Lem:1.2) -> ✅ RELEVAN
   [KARBO] Beras Merah, Nasi (Kal:149.0, Pro:2.8, Lem:0.4) -> ✅ RELEVAN
   [KARBO] Roti Boong (Kal:341.0, Pro:5.5, Lem:16.2) -> ✅ RELEVAN
   [KARBO] Beras Giling Var Pelita, Mentah (Kal:369.0, Pro:9.5, Lem:1.4) -> ✅ RELEVAN
   [KARBO] Beras Giling Var
Rojolele, Mentah (Kal:357.0, Pro:8.4, Lem:1.7) -> ✅ RELEVAN
   [PROTEIN] Telur Ayam Ras, Bagian
 Kuning, Segar (Kal:355.0, Pro:16.3, Lem:31.9) -> ✅ RELEVAN
   [PROTEIN] Telur Ayam, Dadar,
 Masakan (Kal:251.0, Pro:16.3, Lem:19.4) -> ✅ RELEVAN
   [PROTEIN] Ayam Goreng
 Kentucky, Dada (Kal:298.0, Pro:34.2, Lem:16.8) -> ✅ RELEVAN
   [PROTEIN] Ayam Goreng
 Kentucky, Paha (Kal:286.0, Pro:32.1, Lem:16.1) -> ✅ RELEVAN
   [PROTEIN] Telur Ayam Kampung,
 Segar (Kal:174.0, Pro:10.8, Lem:14.0) -> ❌ TIDAK RELEVAN
   [SERAT] Sie Reuboh, Masakan (Kal:474.0, Pro:11.2, Lem:42.5) -> ✅ RELEVAN
   [SERAT] Tumis Keumamah (Kal:300.0, Pro:14.5, Lem:20.0) -> ✅ RELEVAN
   [SERAT] Lawara Jangang,
 Masakan (Kal:159.0, Pro:5.0, Lem:10.9) -> ✅ RELEVAN
   [SERAT] Sayur Lilin-Terubuk (Kal:36.0, Pro:2.7, Lem:0.7) -> ✅ RELEVAN
   [SERAT] Talas Bogor, Kukus (Kal:120.0, Pro:1.5, Lem:0.3) -> ✅ RELEVAN
   📊 Akurasi BULKING: 14/15 Item (93.33%)
------------------------------------------------------

👉 TARGET: MAINTAIN
   [KARBO] Jagung Nasi, Mentah (Kal:357.0, Pro:8.8, Lem:0.5) -> ✅ RELEVAN
   [KARBO] Beras Jagung Kuning, Kering, Mentah (Kal:358.0, Pro:5.5, Lem:0.1) -> ✅ RELEVAN
   [KARBO] Beras Jagung Putih,
Kering, Mentah (Kal:307.0, Pro:4.8, Lem:0.1) -> ✅ RELEVAN
   [KARBO] Jagung, Tepung Putih (Kal:355.0, Pro:9.2, Lem:3.9) -> ✅ RELEVAN
   [KARBO] Jagung Muda, Kuning, Mentah (Kal:147.0, Pro:5.1, Lem:0.7) -> ✅ RELEVAN
   [PROTEIN] Ikan Lais Bakar (Kal:147.0, Pro:17.5, Lem:6.5) -> ✅ RELEVAN
   [PROTEIN] Ikan Baung Bakar (Kal:144.0, Pro:17.8, Lem:5.8) -> ✅ RELEVAN
   [PROTEIN] Telur Aayam Ras,
 Bagian Putih, Segar (Kal:50.0, Pro:10.8, Lem:0.0) -> ✅ RELEVAN
   [PROTEIN] Telur Ayam, Dadar,
 Masakan (Kal:251.0, Pro:16.3, Lem:19.4) -> ✅ RELEVAN
   [PROTEIN] Telur Ayam Ras, Segar (Kal:154.0, Pro:12.4, Lem:10.8) -> ✅ RELEVAN
   [SERAT] Kangkung, Kukus (Kal:30.0, Pro:3.2, Lem:0.7) -> ✅ RELEVAN
   [SERAT] Kangkung, Segar (Kal:28.0, Pro:3.4, Lem:0.7) -> ✅ RELEVAN
   [SERAT] Kangkung, Rebus (Kal:22.0, Pro:2.5, Lem:0.6) -> ✅ RELEVAN
   [SERAT] Kangkung Tondano (Kal:43.0, Pro:1.8, Lem:0.2) -> ✅ RELEVAN
   [SERAT] Pelecing Kangkung (Kal:75.0, Pro:2.5, Lem:2.8) -> ✅ RELEVAN
   📊 Akurasi MAINTAIN: 15/15 Item (100.00%)
------------------------------------------------------

======================================================
 🎯 TOTAL AKURASI SISTEM RAG (MEAN PRECISION) : 97.78%
======================================================

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Ambil satu contoh item sayur dari hasil target "cutting"
contoh_sayur = recommender.get_balanced_basket('cutting')['serat'][0]

# Tampilkan SEMUA isi data mentahnya
print("Isi Mentah Data Sayur di ChromaDB:")
print(contoh_sayur)

Isi Mentah Data Sayur di ChromaDB:
{'nama': 'Kangkung, segar', 'kalori': 28.0, 'protein': 3.4, 'lemak': 0.7, 'karbo': 3.9, 'desc': 'Nama Bahan: Kangkung, segar. Kategori: MENTAH. Nutrisi per 100g: Energi 28.0 kkal, Protein 3.4g, Lemak 0.7g, Karbohidrat 3.9g.'}